### ISSUE TITLE
linux protobuf-c static lib would be nice

### ISSUE THREAD

**Issue by deem0n** [nats-io/nats.c#191]
Hello, I am making [nim wrapper](https://github.com/deem0n/nim-nats) around cnats. It was easy for Mac OS X and very hard for Linux, surprise.

I am testing on CentOS 7, which has outdated protobuf-c and cnats distribution has only dynamic protobuf-c.so. Having static protobuf-c.a would make life easier. could you please include static linux protobuf.a ?

Thank you.

**Comment by kozlovic** [comment]
I tried (and this is why I have macOS and Windows static), but it would fail on Linux on some compilers (notably on the one used by Travis). This is why I ended-up with dynamic for Linux. If you tell me how I need to compile protobuf-c static on Linux so that it works with cnats and compil and tests pass on Travis, I will be happy to include it.

**Comment by deem0n** [comment]
This worked on CentOS 7 without any protobuf* mess installed globally:

```sh
# wget protobuf-cpp-3.6.1.tar.gz
cd protobuf-3.6.1
./configure --disable-shared --prefix=/opt
make && make install

# wget protobuf-c-1.3.1.tar.gz
cd protobuf-c-1.3.1
PKG_CONFIG_PATH=/opt/lib/pkgconfig ./configure --prefix=/opt
make && make install
```

**Comment by kozlovic** [comment]
Thanks, I'll give it a try.

**Comment by kozlovic** [comment]
But then I get this when building cnats:
```
root@aa67f542d523:/home/ivan/cnats/build_linux# make
[  1%] Linking C shared library libnats.so
/usr/bin/ld: ../../pbuf/lib/linux/libprotobuf-c.a(protobuf-c.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
../../pbuf/lib/linux/libprotobuf-c.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/nats.dir/build.make:851: recipe for target 'src/libnats.so.1.8.0' failed
```
I had in the past compiled the protobuf library with -fPIC and it would work on my linux VM (with `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609`) but would fail on Travis which uses a different gcc version (`gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4`).
