### ISSUE TITLE
libprotobuf-c.so: undefined reference to `memcpy@GLIBC_2.14'

### ISSUE THREAD

**Issue by jasonclinx** [nats-io/nats.c#201]
```
../../pbuf/lib/linux/libprotobuf-c.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/nats-subscriber] Error 1
make[1]: *** [examples/CMakeFiles/nats-subscriber.dir/all] Error 2
make: *** [all] Error 2
```

Hi, I tried to `make` cnats and found `libprotobuf-c.so` is not compatible with my local GLIBC version. I was on Redhat 6.4 with a lower version GLIBC 2.12. 

Actually I also downloaded, built and saved GLIBC 2.14 in somewhere on my Redhat. With this new GLIBC, how should I `cmake` cnats? By setting some flags in CMakeLists.txt or environmental variables?

**Comment by kozlovic** [comment]
Sorry, I don't know how to do that. Do you need NATS Streaming API? If not, you could disable the building of Streaming to just build core NATS (which won't require libprotobuf-c.so). To do that, do a `make edit_cache` and toggle `NATS_BUILD_STREAMING` to `OFF`.
If you need Streaming built, try building on a newer system. If I find out how to instruct CMake to link with specific glibc I will update this issue.

**Comment by timcamber** [comment]
I had similar linking issues and (I think) I've solved it by building and including my own `libprotobuf-c.so`. It may seem obvious to you, but it wasn't to me, and I wasted some time until I realized I should just build my own protobuf library, so maybe at least a note could be added to the repo with some explanation?
