### ISSUE TITLE
Bundling precompiled libprotobuf-c 

### ISSUE THREAD

**Issue by ksachdeva** [nats-io/nats.c#205]
Hi,

I can understand that you want to make life easier by keeping all the dependencies in the repo however it may present more problems than it solves.

Take for example -

a) I need to run cnats on arm64v8. Would you provide the binary for it ?
b) You may face some glibc related issues.

Since in C/C++ one has to download the library and compile it anyways it is okay to expect that that developer has libprotobuf-c installed

Regards
Kapil

**Comment by kozlovic** [comment]
@ksachdeva True, but I am not sure what you are suggesting then? Should we make the path to libprotobuf library settable in CMake? Is that what you had in mind?

**Comment by ksachdeva** [comment]
I would say that there are two ways of doing it -

- You can add libprotobuf-c as a submodule so that when one builds cnats then it gets built as well

- Or, use pkgconfig (from your CMake) to discover its headers and libs [this is what I see in their repository ... they are not cmake based build system]

**Comment by loint** [comment]
I think submodules is more convenience, developers are able to build in specific platform.
First time, I used so file but after that I use protobuf-c repository directly :D

**Comment by rigtorp** [comment]
It's quite strange to bundle the actual binary for libprotobuf-c in this repository. You can vendor the code for libprotobuf-c and build a static library when building nats.c. Also allow using system installed libprotobuf-c using a cmake option().

**Comment by kozlovic** [comment]
I hear you all. I wanted to make it easy for users to start with streaming, but I realize that this was probably not the right approach. I will make it a default to link to installed libprotobuf-c (user will have to install/compile on their own). I may, optionally through a cmake option, allow user to use the one provided - unless I decide to remove the precompiled lib from this repo :-)
