### ISSUE TITLE
Linux gcc 5.4.0 SSL connections fail (with valgrind) to server 1.4.0+

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats.c#212]

**Comment by ziyht** [comment]
...

**Comment by kozlovic** [comment]
Note: this is an issue when running the test suite (ctest) with valgrind (ctest -T memcheck). It started to appear when Travis updated gcc from 4.8.4 to 5.4.0.

**Comment by kozlovic** [comment]
Works with valgrind 3.15.. will have to find a way to make Travis download 3.15 instead of 3.11 which has the issue. Closing for now.
