### ISSUE TITLE
Can Cnats streaming client be used with libuv

### ISSUE THREAD

**Issue by 06wagon** [nats-io/nats.c#214]
Hi,
Can Cnats streaming client be used with event loop? such as libuv or libevent.

**Comment by kozlovic** [comment]
The streaming layer uses the NATS connection to communicated with the server (see [here](https://github.com/nats-io/nats-streaming-server#relation-to-nats) for some background).

So you could configure the options to use an event loop and pass those options to the Streaming API connect's call. It will create a NATS connection internally and use given options, therefore should be able to use the event loop. Let me know if you have issues.
