### ISSUE TITLE
nats.c is using blocking sockets and select with infinite timeouts

### ISSUE THREAD

**Issue by rigtorp** [nats-io/nats.c#217]
See #215 for the concrete bug. This issue is a discussion on how to handle use sockets with unreliable networks in general.

I see in `natsSock_ConnectTcp` care was taken to handle connection timeout correctly by setting socket to non-blocking and then using `select` to wait with a timeout. That is all good but it's possible to block indefinitely by mistake if `ctx->deadline` was not set before calling `natsSock_ConnectTcp`; in which case `natsSock_WaitReady` will block forever. It would be a good idea to make it impossible to introduce a bug like that.

Later in `_processConnInit` the socket is set back to blocking mode again. I think that is misguided it allows future read and write operations to block. Instead `select` (or equivalent) should be used to make sure all operations will timeout.

**Comment by kozlovic** [comment]
I am looking at leaving in non blocking mode and make use of the deadline facilities that I have. It would have to be introduced with new option though - as to not break existing apps, and likely be a timeout value passed as an option (since now publish calls could fail, etc..).
Keeping this opened while I investigate a bit more.

**Comment by rigtorp** [comment]
I recommend requiring `libuv` and using it's event loop it solves most portability issues and gives a nice IO architecture. In my experience socket IO works best when read and writes are done on the same thread multiplexed by epoll, this pattern also allows high performance settings with onload kernel bypass. Check out the IO architecture of zeromq. If you use 1 thread per connection you will also be able to get a nice boost by using io_uring in the future (I predict especially for small messages due to less context switches).

**Comment by rigtorp** [comment]
Some relevant info https://idea.popcount.org/2019-09-20-when-tcp-sockets-refuse-to-die/

**Comment by kozlovic** [comment]
I am in the process of adding a write deadline option. In case of timeout, the socket will be closed forcing a reconnect (if allowed).

**Comment by kozlovic** [comment]
Here is the branch I previously mentioned: https://github.com/nats-io/nats.c/tree/add_write_deadline.
I *think* that it would address some of your concerns. If there is a write timeout, the socket will be closed to trigger a possible reconnect.

**Comment by rigtorp** [comment]
Yes this should work.
