### ISSUE TITLE
CI builds use old gcc and clang

### ISSUE THREAD

**Issue by rigtorp** [nats-io/nats.c#219]
GCC9 detects many string truncation issues that could be fixed

**Comment by kozlovic** [comment]
@rigtorp Thank you for all these reports. I am a bit swamped at the moment, so any of those reports that you think you can contribute, please don't hesitate to send PRs. I will review as soon as I can. Thanks!

**Comment by rigtorp** [comment]
@kozlovic Yes I don't expect prompt fixes. I'm fixing some of the stuff that causes issues for me in production.

**Comment by kozlovic** [comment]
Built upon your PR and we now have gcc-9 and clang-8 with sanitizer running. The warnings have been fixed in #239
