### ISSUE TITLE
Potential race on file descriptor in conn.c

### ISSUE THREAD

**Issue by rigtorp** [nats-io/nats.c#224]
In `_close()` the socket is closed before all threads have been join. I don't see how a race on the fd is prevented. After calling _close() it's still possible for the reader thread to use the fd which could have already been reused by a new socket/file. In general it's best to protect fds by a reader-writer lock, open and close operations take the writer lock, read and write operations take the read lock.

**Comment by rigtorp** [comment]
Same issue exist in `_readLoop()`. Socket is closed without making sure that flusher thread is not using the socket.

**Comment by kozlovic** [comment]
No, I shutdown the socket, not close it and let the readLoop do that: https://github.com/nats-io/nats.c/blob/master/src/conn.c#L2139

**Comment by rigtorp** [comment]
What prevents the writer from using the socket before this line https://github.com/nats-io/nats.c/blob/master/src/conn.c#L1861

**Comment by kozlovic** [comment]
What writer? If the connection has been closed, no new publish call/flush can happen.

**Comment by rigtorp** [comment]
When I reach this line https://github.com/nats-io/nats.c/blob/master/src/conn.c#L1861 have the flusher thread been joined?

**Comment by kozlovic** [comment]
Yes, the _close() will join threads: https://github.com/nats-io/nats.c/blob/master/src/conn.c#L2103
but even then, since the connection is marked closed, and connection and flusher use the connection lock, the flusher would not try to flush (write) if the connection is marked as closed (https://github.com/nats-io/nats.c/blob/master/src/conn.c#L1907)

**Comment by rigtorp** [comment]
Here the socket seems to be closed without joining the flusher thread first https://github.com/nats-io/nats.c/blob/master/src/conn.c#L2130

**Comment by kozlovic** [comment]
It means that there is no readloop, so likely the connection was not created properly, but again, it does not matter because the connection is marked as closed under connection lock and flusher will verify before trying to write.

**Comment by rigtorp** [comment]
I see now that the flusher thread is actually holding the conn lock while writing, so there is no race when closing in the read loop. But it's problematic since it can cause publishers to wait indefinitely on the conn lock, effectively blocking on the socket with no way for the application to deal with slow broker. Also with this design for every `natsConnection_Publish()`  call there will be a FUTEX_WAKE call, removing a lot of advantage of enqueuing sends. So the flusher basically is a user space implementation of TCP_CORK.

If conn had a lock free MPSC queue `natsConnection_Publish()` could be made non-blocking and would only need to do a FUTEX_WAKE if the flusher thread is quiescent. If socket is in writable state the calling thread could also short-circuit the flusher thread and write directly to the socket (until it returns EAGAIN), but that should be optional since it would lower latency but reduce throughput for the caller.
