### ISSUE TITLE
Replace calls to "ASN1_STRING_data" with "ASN1_STRING_get0_data"

### ISSUE THREAD

**Issue by danesh-d** [nats-io/nats.c#228]
According to recommendation from OpenSSL (see here https://www.openssl.org/docs/man1.1.0/man3/ASN1_STRING_data.html) the function "ASN1_STRING_data" is deprecated and should be replaced by "ASN1_STRING_get0_data".

**Comment by kozlovic** [comment]
Closed due to PR #238.
