### ISSUE TITLE
Understanding the reconnection logic

### ISSUE THREAD

**Issue by arun11299** [nats-io/nats.c#232]
Hi,
I am trying to evaluate NATS for our needs. I have this test setup:
1. A standalone NATS server (v2.0.0)
2. A Client written in C++ using the async adapters to hook into CoreFoundation runloop.

The issue is that, when I restart the NATS server, the client tries to reconnect with the server only the first time. After I restart the NATS server the second time, there is no attempt made to reconnect until the ping request is sent.

Here is how my attach callback looks like:
```
void AsyncNatsClient::on_attach_cb(natsConnection* nc, natsSock sock)
{
  std::cout << "ARN: on_attach_cb: " << sock << std::endl;;
  connection_ = nc;
  CFSocketContext socket_ctx = { 0, this, nullptr, nullptr, nullptr };

  cleanup_socks();
  cleanup_subscriptions();

  connection_ = nc;
  nats_sock_ = static_cast<int>(sock);

  client_sock_ref_ = rwsched_tasklet_CFSocketCreateWithNative(
      tasklet_,
      kCFAllocatorSystemDefault,
      nats_sock_,
      kCFSocketReadCallBack | kCFSocketWriteCallBack,
      nats_async_connection_event_cb,
      &socket_ctx);
  RW_ASSERT (client_sock_ref_);

  source_ref_ = rwsched_tasklet_CFSocketCreateRunLoopSource(
      tasklet_, kCFAllocatorSystemDefault, client_sock_ref_, 0);
  RW_ASSERT (source_ref_);

  rwsched_CFRunLoopRef runloop = rwsched_tasklet_CFRunLoopGetCurrent(tasklet_);

  rwsched_tasklet_CFRunLoopAddSource(
      tasklet_, runloop, source_ref_, sched_->main_cfrunloop_mode);
}
```
And this is how I am setting up the callbacks:
```
natsOptions_SetDisconnectedCB(options_, disconnect_cb,       this);
  natsOptions_SetReconnectedCB(options_,  reconnect_cb,        this);
  natsOptions_SetClosedCB(options_,       perm_conn_closed_cb, this);
  natsOptions_SetErrorHandler(options_,   error_cb,            this);
  natsOptions_SetPingInterval(options_, 10000);

  // Reconnection options
  natsOptions_SetMaxReconnect(options_, MAX_RECONNECT_ATTEMPTS);
  natsOptions_SetReconnectWait(options_, RECONNECT_WAIT_TIME_MS);

  natsStatus s = natsOptions_SetEventLoop(options_, (void*)this,
                                          attach_cb,
                                          read_cb,
                                          write_cb,
                                          detach_cb);
```

After the second connection loss (after the 2nd NATS server restart), it results in call to periodic disconnect and reconnect callback calls  whenever the ping request is sent:
```
rift# ARN: read cb
ARN: write cb
ARN: disconnected
ARN: connect cb
ARN: on_attach_cb: 43
ARN: write cb
ARN: reconnect cb
ARN: read cb
ARN: write cb
ARN: disconnected
ARN: connect cb
ARN: on_attach_cb: 77
ARN: write cb
ARN: reconnect cb
```
The numbers 43 and 77 are the socket descriptors. So, it seems like it is trying to setup new connection and failing ?
What is the right way to handle reconnects ?

Thanks in advance!

**Comment by arun11299** [comment]
@kozlovic Can you please share your views on this ?

**Comment by kozlovic** [comment]
@arun11299 I was on vacation, will take a look asap.

**Comment by arun11299** [comment]
@kozlovic Sorry for not updating. But, I found the issue.
The problem was basically that for the new socket, it started the loop on the thread on which the callback was called, which was basically the libraries reconnecting thread.
If I am right, this thread is short lived and thus the event loop to which the new fd was added got also disabled or removed.

**Comment by kozlovic** [comment]
Glad you found the issue. Yes, when the library detects the disconnect and try to reconnect, there is a short lived thread that deals with reconnection. The library will invoke the attach callback from that thread indeed.
