### ISSUE TITLE
Why callback function should be static?

### ISSUE THREAD

**Issue by danesh-d** [nats-io/nats.c#233]
@kozlovic I am wondering why callback function which is called upon receiving a message by subscriber should be defined as static? Considering completely different meaning of static in C and C++, defining the callback as static in C would be reasonable but when you subscribe in C++ you still should define the callback as static which make the whole class to behave differently and also will restrict the access to the received message. Is there any workaround for the case when library is used in C++?

**Comment by kozlovic** [comment]
I am not sure I understand the problem. The library is not forcing the message callback to be defined as static (true that most tests and examples do, but that's not a requirement). 
I am not knowledgeable in C++, but since it is object oriented, I guess that you could create an object and pass the object's msg callback to the subscribe call.

**Comment by danesh-d** [comment]
Actually we subscribe to the function as:

`s = natsConnection_Subscribe(&sub, nc, "foo", onMsg, nullptr);`

and the callback is defined as:

`onMsg(natsConnection *nc, natsSubscription *sub,natsMsg *msg, void *closure)`

The problem is that if the callback is not defined as static, then compiler will return the following error:

`invalid use of non-static member function`

The problem solved only when the callback is defined as static. I suspect that there is some mismatch between C and C++ when callback's signature is defined in nats.c.

**Comment by kozlovic** [comment]
If onMsg() is generic, then I guess you can make it static. But if it is part of an object, then you should probably pass it like `myObj->onMsg` or something similar, no?

**Comment by zzh1414080903218** [comment]
you can sub such as:
s = natsConnection_Subscribe(&sub, nc, "foo", onMsg, this);
onMsg function do:
SomeClass *obj = (SomeClass*)closure;
obj->onMsg(...);

**Comment by danesh-d** [comment]
@kozlovic The callback is actually part of the same class that subscribes to Nats so it can directly be called e.g. onMsg or this->onMsg. The problem is that the subscribe function in Nats expects (apparently) to get a static function. I looked quickly in example codes and in those codes on Nats (written in C of course) the callback is always static, but this would not give much info since static in C and C++ are completely different, so you may define a function as static in C or not and it does not really matter how you refer to it, but in C++ it does, since a static function in C++ will not need the class to be instantiated and hence will have very limited access to the data within the class. It might be needed to update at least the function signatures of publish and subscribe functions in Nats.c to fix this problem.

**Comment by danesh-d** [comment]
@zzh1414080903218 You mean as a workaround, move the functionality to another class and instantiate it in the static function? Well, I don't know! It might work, but a new layer will be added if I have understood what you mean, correctly.

**Comment by danesh-d** [comment]
FYI, the problem seems to be here:

typedef void (*natsMsgHandler)(natsConnection *nc, natsSubscription *sub, natsMsg *msg, void *closure);

where the function signature of callback for subscription is defined. The signature requires only static functions when the subscription is done in C++.

**Comment by kozlovic** [comment]
@danesh-d Nowhere in that `typedef` do I specify static. I am not sure what you are asking the C library to do here? I am sure plenty of people use the C library with C++ applications and they have never reported an issue. Maybe the way to do in C++ is indeed as @zzh1414080903218 suggested.

The subscribe call needs a message callback, and can take a closure. If your object supposed to deal with given subscription cannot have a function with the "onMsg" signature as defined in the C library, then I guess the option of using a onMsg() and then casting the closure to your object and then invoking that object's message handler implementation may work.

**Comment by zzh1414080903218** [comment]
@danesh-d Don't need another class,give you object for closure.You can get your object in static onMsg function,and then you can do your object's onMsg.

**Comment by danesh-d** [comment]
@kozlovic and @zzh1414080903218 Many thanks for your kind advises! As you mentioned we use closure and passed `this` and then called other private methods within the class to perform callback operations. No extra class was needed and only reference to the class itself was enough. Thanks again.
