### ISSUE TITLE
How to get error info on errorCallback?

### ISSUE THREAD

**Issue by zzh1414080903218** [nats-io/nats.c#234]
errorCallback only has err(natsStatus) but I want to error msg,and nats_GetLastError return null.How to do?

**Comment by kozlovic** [comment]
@zzh1414080903218 Sorry to ask, which error callback are you referring to? I think I usually allow a closure in all callbacks..

**Comment by zzh1414080903218** [comment]
typedef void (*natsErrHandler)(
        natsConnection *nc, natsSubscription *subscription, natsStatus err,
        void *closure);
This error callback,it has only natsStatus type,I need more information,like "NATS_NOT_PERMITTED"

**Comment by kozlovic** [comment]
@zzh1414080903218 I am sorry, I still don't understand what you are asking. `natsStatus` is the possible error that this callback is invoked with. `NATS_NOT_PERMITTED` for instance, is a `natsStatus`.

**Comment by zzh1414080903218** [comment]
natsStatus is a number,but I want to get the string.

**Comment by kozlovic** [comment]
Look at `natsStatus_GetText()`...

**Comment by zzh1414080903218** [comment]
Sorry! I missed this function...Thanks!
