### ISSUE TITLE
Can't build it for windows target

### ISSUE THREAD

**Issue by IgorKey** [nats-io/nats.c#235]
Hi there. 
All my tries with compile these stuff give these errors.
undefined reference to `SSL_read'
undefined reference to `SSL_get_error'
undefined reference to `ERR_get_error'
undefined reference to `ERR_reason_error_string',

I've downloaded the openSSL and add it to paths, also link.txt contains these 
C:/OpenSSL-Win64/lib/libssl.lib C:/OpenSSL-Win64/lib/libcrypto.lib etc.
What the problems?May be Do you have already built binaries?

**Comment by kozlovic** [comment]
I am using CMake to build cross-platform and I just tested and can compile ok on Windows. Please follow instructions [here](https://github.com/nats-io/nats.c#building). For instance, if you don't plan to use TLS, you can compile that out.
