### ISSUE TITLE
FD_SETSIZE hack in glibc can cause memory corruption.

### ISSUE THREAD

**Issue by s-shin** [nats-io/nats.c#243]
Current implementaion [redefines `FD_SETSIZE` to 32768](https://github.com/nats-io/nats.c/blob/v2.0.0/src/include/n-unix.h#L27-L30) in Linux, but this hack can lead to undefined behavior in glibc.

`man 2 select` says

> BUGS
>
>       POSIX allows an implementation to define an  upper  limit,  advertised  via  the  constant
>       FD_SETSIZE,  on  the  range of file descriptors that can be specified in a file descriptor
>       set.  The Linux kernel imposes no fixed limit, but the glibc implementation makes fd_set a
>       fixed-size  type,  with  FD_SETSIZE  defined  as  1024,  and  the  FD_*() macros operating
>       according to that limit.  To monitor file  descriptors  greater  than  1023,  use  poll(2)
>       instead.
>
> http://manpages.ubuntu.com/manpages/bionic/en/man2/select.2.html

I also give you a project for the reproduction of this issue.
https://github.com/s-shin/libnats-select-issue

AFAIK, the only one solution is using `poll`/`epoll` instead of `select`.

**Comment by kozlovic** [comment]
Thank you for the report. I will look into this as soon as I can.

**Comment by kozlovic** [comment]
As a side note, I noticed your fix for the missing include. Thanks for that! I did not have problem building before because of building with Streaming support. When streaming is built, one of the header we include does contain the missing include, so build ok. When building with streaming OFF, then it failed to build. The call to offsetof() was added in v2.0.0, so pretty recent.
Anyway, I have added issue #248 and submitted PR #249 for the fix.

**Comment by s-shin** [comment]
@kozlovic I created a reference implementation using epoll. https://github.com/s-shin/nats.c/commit/934f5e2a062a13b878a0f0edb3658d59c14171be
(Since it is the first time I use epoll API directly, bugs will be included :D)
In my some tests, this change seems to get rid of the crash.
I hope it may help you.

**Comment by s-shin** [comment]
Any updates?
I think this issue is quite critical in practical use.

**Comment by kozlovic** [comment]
@s-shin Working on that (an many other things in other repos).. thank you for your patience. I think that you have a temp fix using poll. This is probably the direction that I am going to go.

**Comment by s-shin** [comment]
Great job! Thank you for your prompt fix.
