### ISSUE TITLE
TLS  - Using cert content instead of file location

### ISSUE THREAD

**Issue by arajitsamanta** [nats-io/nats.c#267]
Hi All,

**This is not an issue. I am just trying to see if i there is any other approaches for TLS connection**

I am trying to use NATS C library to connect to a NATS cluster via TLS . I am able to successfully connect it using following method

```c
natsOptions_LoadCertificatesChain(opts,certChainFilePath,keyFilePath);
```
I want to know if there is anyway i can pass the cert and key file content as character array rather than passing the file path which is file system path. Reason being i am looking for such option is that for security reason i cant simply have the cert and key file on the host file system.

My plan is to have the cert and key file in some db(sqllite) and read the content from DB and pass it to natsOptions_LoadCertificatesChain() method.

Any help or suggestions ?

Thanks,
Arajit

**Comment by kozlovic** [comment]
I have a branch (https://github.com/nats-io/nats.c/tree/add_load_cert_and_key_from_memory) which adds this ability through a new option: natsOptions_LoadCertificateAndKey(). Interested in your feedback and if you could try by building from this branch it would be great.
I am not sure of the signature (right now requires the cert and key to be a NULL terminated string containing the certificate and key). I may change it to a `(const void*)` and require the length. Let me know what you think. Thanks!

**Comment by arajitsamanta** [comment]
@kozlovic Thanks for quick response. let me try with this branch.

**Comment by arajitsamanta** [comment]
@kozlovic This solution work like a charm!!

One more question I have is that can we have similar functionally be added for ```natsOptions_LoadCATrustedCertificates()``` method as well ?

**Comment by kozlovic** [comment]
@arajitsamanta I did, but also changed the name for the one for client cert/key. I used `natsOptions_SetCATrustedCertificates()` and `natsOptions_SetCertificatesChain()` as opposed to the `natsOptions_LoadX()` options.

**Comment by kozlovic** [comment]
(note I have push forced the branch and submitted a PR, so if you want to try you may have to reset/checkout the branch again).

**Comment by arajitsamanta** [comment]
I tested it and it works smoothly. Wondering when this will be available in an official release so that i can use it.

**Comment by kozlovic** [comment]
@arajitsamanta Hopefully soon. I need to merge another PR under review and may submit something too before the next release. So may have a release this week or next.

**Comment by arajitsamanta** [comment]
@kozlovic Thank you for making this happen. I will keep an eye on the next release.
