### ISSUE TITLE
Event loop with nats streaming

### ISSUE THREAD

**Issue by loint** [nats-io/nats.c#283]
Hi @kozlovic ,

Currently, we're using libuv to avoid creating threads for nats streaming because of thousand durable subscriptions.

When we use `stanConnection_Connect`, it raised an error 'timeout' as metioned in README related to `natsConnection_Request` should not be called inside event loop.

I'm trying to make separate thread but not sure if it breaks other functionality
```
snprintf(discoverySubj, sizeof(discoverySubj), "%s.%s", sc->opts->discoveryPrefix, clusterID);
s = natsConnection_Request(&replyMsg, sc->nc, discoverySubj, reqBytes, reqSize, sc->opts->connTimeout);
```

So do you have any advice in this case ?

**Comment by kozlovic** [comment]
There is no way I can think of this could work. Streaming uses heavily request/reply to communicate with the server and the library is not going to work with libuv.

We do have an option in the library to use a pool of threads to dispatch subscriptions messages (and avoid creating a thread per subscription). In Streaming, the streaming connection still creates some internal subscriptions and prevent those to use the thread pool, but internal subscriptions for the streaming subscriptions *should* be able to use this pool. Look for `nats_SetMessageDeliveryPoolSize()` in the readme's FAQ and see if that works for you. Thanks!

**Comment by loint** [comment]
Thanks
