### ISSUE TITLE
[Windows static] DllMain is defined in static builds

### ISSUE THREAD

**Issue by emgre** [nats-io/nats.c#284]
The `DllMain` symbol is defined even in static builds. I have another library that does the same error and I get a duplicate symbol error when linking.

The issue #68 already brought this problem and the suggested fix in #69 was sufficient (I think), but the `#ifndef` was removed in #70 that superseeded #69. Some `#ifdef`/`#endif` trickery here and in the header should probably do the trick: https://github.com/nats-io/nats.c/blob/7e1807cb7491fc4cc34e2b05cc8faec1bf15b046/src/nats.c#L208-L235

cc @jadamcrain

**Comment by kozlovic** [comment]
@emgre I have submitted PR #285 that exclude DllMain when compiling the static library. However, I am not sure what you mean about: `and in the header`? What should I exclude/include with `#ifdef` in a header, and which header?

**Comment by emgre** [comment]
Forget about the "and in the header", I just assumed there was a declaration of `DllMain` in `nats.h`, but that doesn't make sense, sorry about that. Your fix looks great to me, thanks for the quick response!
