### ISSUE TITLE
there is a bug in /adapters/libuv.h 

### ISSUE THREAD

**Issue by hubinix** [nats-io/nats.c#290]
https://github.com/nats-io/nats.c/blob/master/src/adapters/libuv.h

**Comment by hubinix** [comment]
static void
natsLibuvPoll(uv_poll_t* handle, int status, int events)
{
    natsLibuvEvents *nle = (natsLibuvEvents*)handle->data;

    if (status != 0)
        return;

    if (events & UV_READABLE)
        natsConnection_ProcessReadEvent(nle->nc);

    if (events & UV_WRITABLE)
        natsConnection_ProcessWriteEvent(nle->nc);
}
when this code is running on linux,
and the network disconnected, status will be -9 ,
so the the network disconnected can not be detected,so auto reconnect will not happen.

**Comment by hubinix** [comment]
i don't know how to fix it better,but i change this code block like this:
if (status != 0) {
		if (status == -9) {
			natsConnection_ProcessDisconnectEvent(nle->nc);
		}
		return;
	}
the "natsConnection_ProcessDisconnectEvent" just like natsConnection_ProcessReadEvent,but the 
_processOpError is always called in this function

**Comment by kozlovic** [comment]
I think calling `natsConnection_ProcessReadEvent()` in that case would work as good, and we don't need to add a new function. I just tested this scenario and it works (please try that too):
```
if (status != 0)
{
    natsConnection_ProcessReadEvent(nle->nc);
    return;
}
```
