### ISSUE TITLE
Build w/ NATS Streaming Fails

### ISSUE THREAD

**Issue by hikingmoose** [nats-io/nats.c#297]
When trying to build nats.c-2.1.0 w/ streaming enabled I am getting the following errors (Currently using protobuf-c-1.3.2)

**Ran the following commands:**
cmake .. -DNATS_PROTOBUF_DIR=/usr/local/include -DNATS_PROTOBUF_LIBRARY=/usr/local/lib/libprotobuf-c.so.1.0.0 -DNATS_BUILD_WITH_TLS=OFF
make install
**Errors:**
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_empty_string"
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_message_pack"
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_message_pack_to_buffer"
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_message_unpack"
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_message_get_packed_size"
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_message_free_unpacked"

**Note:** it was able to find the library "-- Found libprotobuf-c: /usr/local/include" and it is not complaining that it can't find the protobuf-c.h file, just that it has undefined references. I also tried nats.c-2.0.0 and different versions of protobuf-c but have issues no matter what combination I use, until I go back to nats.c-1.8.0 where it came packaged together.

**Comment by kozlovic** [comment]
Are you sure that you are using protobuf-c 1.3.2? Because you are pointing to library 1.0.0:
```
-DNATS_PROTOBUF_LIBRARY=/usr/local/lib/libprotobuf-c.so.1.0.0
```
Which platform are you building on? If libprotobuf is installed, you should not have to specify any of the `-D DNATS_PROTOBUF_xxx` param.

**Comment by hikingmoose** [comment]
Hmm...that's a good point. I built and installed protobuf-c 1.3.2 (Did not have any other versions installed previously) and that is what it installed (timestamp is correct and everything). Not sure why they use that naming convention.

I am building on CentOS 7.6.

I just tried again without the -D params and you are right that it finds the libs without it, but I still get the same errors unfortunately. I also tried building nats.c-2.0.0 with the same result. 


[ 77%] Building C object src/CMakeFiles/nats_static.dir/stan/sub.c.o
Linking C static library libnats_static.a
[ 77%] Built target nats_static
Scanning dependencies of target nats-asynctimeout
[ 78%] Building C object examples/CMakeFiles/nats-asynctimeout.dir/asynctimeout.c.o
Linking C executable nats-asynctimeout
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_message_pack"
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_empty_string"
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_message_get_packed_size"
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_message_free_unpacked"
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_message_pack_to_buffer"
../src/libnats.so.2.1.0: undefined reference to "protobuf_c_message_unpack"
collect2: error: ld returned 1 exit status
make[2]: *** [examples/nats-asynctimeout] Error 1
make[1]: *** [examples/CMakeFiles/nats-asynctimeout.dir/all] Error 2
make: *** [all] Error 2

**Comment by kozlovic** [comment]
If you have install protobuf-c just for this test, what you could do is this: uninstall (remove it) and instead git clone the dependencies repo that I use to build on Travis: https://github.com/nats-io/nats.c.deps.
Clean your build repo (rm CMakeCache.txt) and then `cmake .. -DNATS_PROTOBUF_DIR=<dir to where you have cloned the said repo>/pbuf`. Let me know if this helps.

**Comment by hikingmoose** [comment]
Interestingly enough it finds libprotobuf-c in that pbuf folder but says it can't find the protobuf-c.h until I put it back in /usr/local/include.

**Comment by kozlovic** [comment]
I tried on a CentOS docker image and using NATS C Client master branch. The installed version of protobuf-c(-devel) was definitively too old. I then uninstall and pointed to the dependency repo I mentioned. The weird part is that the code I have in CMakeFiles.txt to detect the libprotobuf-c or pass the NATS_PROTOBUF_DIR/LIBRARY to command line works perfectly on macOS, Windows and Linux (Ubuntu), actually used in the Tavis build, but did not work on CentOS. I had to manually edit the CMakeFiles.txt to set the `NATS_PROTOBUF_INCLUDE_DIRS` and `NATS_PROTOBUF_LIBRARIES` params, and then it worked.

Were you able to compile the library or not?

**Comment by hikingmoose** [comment]
I was just able to get it to build by setting: option(NATS_BUILD_EXAMPLES "Build examples" OFF)
And also removing these two test sub-directories in the CMakeFiles.txt
add_subdirectory(test)
add_subdirectory(test/dylib)

but then I just tried your method for manually setting the params and it works without needing to change anything else! Thanks for taking a look into this!
