### ISSUE TITLE
Libuv and nats-c reconnects

### ISSUE THREAD

**Issue by pananton** [nats-io/nats.c#298]
Hello! I'm not sure whether this it the right place to ask questions about library design, so please excuse me if it is not. My question is about usage of libuv event loop with library. I'm not very familiar with libuv, but afaik its uv_run(UV_RUN_DEFAULT) will exit when no active handles remain (in case of nats - probably when it's connection is closed). Does this mean, that if nats connection which is configured to automatically reconnect gets closed, uv_run(UV_RUN_DEFAULT) will exit and it should be restarted for reconnects to actually take place? Or maybe library handles this on it's own and uv_run does not return until all reconnect attempts are exhausted and connection is permanently closed?

**Comment by pananton** [comment]
Found a maillist, will post this question there.

**Comment by kozlovic** [comment]
@pananton I did send an answer to the Google mailing list, but next time, don't hesitate to ask your question on GitHub, it is not a problem and I find it easier. We can always label the issue as a "Question", so don't worry about it. Thanks!

**Comment by pananton** [comment]
Thank you!
