### ISSUE TITLE
send double array

### ISSUE THREAD

**Issue by jjangchan** [nats-io/nats.c#301]
If you receive a double array [1024] from a subscriber, why is the data corrupted after the 257 index?

1. pubmsg

s = natsConnection_Publish(conn, "foo", g_pAIAcce, _msize(g_pAIAcce) / sizeof(double));
	
2. sub

datas = new double[natsMsg_GetDataLength(msg)];
datas = natsMsg_GetData(msg);
dwSampleCount = natsMsg_GetDataLength(msg);

**Comment by kozlovic** [comment]
I think you are sending with the wrong size. `natsConnection_Publish()` accepts a byte array, so you have to provide the total size of bytes being sent. The `/ sizeof(double)` seem wrong to me.

Here is an example how to send:
```
    double  data[1024];
    int     i;

    for (i=0;i<1024;i++)
        data[i] = (double)(i+1);
    
    s = natsConnection_Publish(conn, subj, (const void*) data, sizeof(data));
```
The `sizeof(data)` would be 8192, which is indeed 1024*8.

And here is how to receive:
```
    double  *data = NULL;
    int     count = 0;
    int     i;

    count = natsMsg_GetDataLength(msg)/sizeof(double);
    data  = (double*) natsMsg_GetData(msg);

    for (i=0; i<count; i++)
        printf("i=%d val=%f\n", i, data[i]);
```
And the output will be:
```
i=0 val=1.000000
i=1 val=2.000000
i=2 val=3.000000
i=3 val=4.000000
i=4 val=5.000000
i=5 val=6.000000
i=6 val=7.000000
i=7 val=8.000000
i=8 val=9.000000
i=9 val=10.000000
i=10 val=11.000000
i=11 val=12.000000
...
i=1019 val=1020.000000
i=1020 val=1021.000000
i=1021 val=1022.000000
i=1022 val=1023.000000
i=1023 val=1024.000000
```

**Comment by jjangchan** [comment]
Solved. Thank you !
