### ISSUE TITLE
Problems parsing message header with extra whitespace

### ISSUE THREAD

**Issue by uscorchr** [nats-io/nats.c#304]
I'm using this client with Jetstream and it has problems parsing some of the reply message headers. For example if I send $JS.INFO, the reply header is something like:

[MSG _INBOX.4T1NQCK347QAA6VRDLVPSV.1 1  186]

Note that there's an extra space in front of the size field. _processMsgArgs() in parser.c treats this as a protocol error and the message is discarded.

**Comment by kozlovic** [comment]
Thank you for the report, I will fix asap.
