### ISSUE TITLE
natsConnection_FlushTimeout strange behaviour

### ISSUE THREAD

**Issue by pananton** [nats-io/nats.c#309]
Hello, sorry for bothering you again. I've found some strange behaviour of natsConnection_FlushTimeout, can you please explain, whether it is expected or I should look futher to my code?
I have a test, that connects to single-node nats "cluster". In natsOptions I set indefinite auto-reconnect for this connection. When connection is established (natsConnection_Status equals NATS_CONN_STATUS_CONNECTED at that time) I stop nats server process to simulate disconnect and wait until connection status changes to any other state except NATS_CONN_STATUS_CONNECTED. Finally, I perform following operations:
```
std::cout<<"BEFORE FLUSH: "<<(int)natsConnection_Status(conn)<<"\n";
natsResult = natsConnection_FlushTimeout(conn, timeout); // timeout is 50 seconds
std::cout<<"FLUSH RESULT: "<<(int)natsResult<<", "<<(int)natsConnection_Status(conn)<<"\n";
```

Next, one of the following situations occur:
1. flush is finished immediately and I see following output:
```
BEFORE FLUSH: 4 // conn status is NATS_CONN_STATUS_RECONNECTING 
FLUSH RESULT: 10, 4 // result is NATS_CONNECTION_DISCONNECTED, conn status is the same
```

2. flush is finished by timeout (50 seconds) and I see the following output:
```
BEFORE FLUSH: 4  // conn status is  NATS_CONN_STATUS_RECONNECTING
FLUSH RESULT: 26, 4 // result is NATS_TIMEOUT, conn status is the same
```

Can you give some feedback what can be the reason? I've tried to set big interval between reconnect attempts and sleep some time to allow first reconnect attempt to fail and only then call flush function but this did not help.

**Comment by kozlovic** [comment]
The first outcome explanation is this: the Flush() sent a PING to the server but before receiving the PONG, the disconnect occurs. So the reconnect thread fails all pending Flush() operations. You will see Flush() failing with NATS_CONNECTION_DISCONNECTED.

The second outcome explanation is that you call Flush() after the reconnect thread has started the reconnect logic and switched the connection's write buffer to a memory buffer, which collects all outbound protocols while in the process of reconnecting. So a Flush() call at that time is simply adding a PING to the outgoing buffer. If the NATS Server is restarted and the reconnect succeeds, the pending buffer will be flushed (including the PING from the Flush() call) and the corresponding PONG will be received which will release the Flush() call. I assume that in your test you are not restarting the NATS Server so the Flush() call will timeout.

**Comment by pananton** [comment]
Yep, that's true - I'm not restarting nats server to test whether flush will actually fail (as it should). I was a little confused that in both cases connection status is reconnecting right before flush call. With your help I've fixed my test in the following way:
1. Set big reconnect attempt interval (10 seconds)
2. Wait for a little (500 ms) after nats server is stopped and connection is moved to reconnecting state to be sure, that first reconnect attempt will fail before I'll initiate flush and does not start again (because of high reconnect attemp interval).

Now test constantly passes as I expect. Is it a correct solution from your point of view?

**Comment by kozlovic** [comment]
Yes if you don't want to handle "immediate" return with a disconnected error status. Both outcome are valid in my opinion.

**Comment by pananton** [comment]
Thank you very much! Btw, can you also tell me whether nats.c or libuv adapter has any special signal handling? Can't find the reason, why my connection closed cb (natsOptions_SetClosedCB) does not get called if SIGTERM is received by process statically linked with nats.c and libuv. I have one subscription (and it's close cb is called), but can't see the same for connection closed cb. The project I'm working on is a pretty big mess, probably I just can't find the place where signal handling brokes. But maybe it's some known issue for you.

**Comment by pananton** [comment]
Forget to mention that with SIGINT everything works as expected.

**Comment by kozlovic** [comment]
The library is not trapping any signal, just ignoring SIGPIPE. So if you want to close connection(s) on SIGINT or SIGTERM, you have to trap it and then do proper cleaning.

**Comment by pananton** [comment]
Ok, thanks!
