### ISSUE TITLE
Slow consumer problem

### ISSUE THREAD

**Issue by pananton** [nats-io/nats.c#317]
Hello, I've found a strange error in my code, can you please explain how slow consumer detection works on nats server side? I set indefinitite incoming buffer size (-1 was used as a argument for both parameters to SetPendingLimits when subscription was created) and my consumer experienced a burst high load of about 100K-200K messages (each one is about 0.5K size) sent in a loop from publisher. NATS server closed connection marking consumer as slow. I have following questions:
1) Library documentation says that client will signal to server that it starts dropping messages because of insufficient space in incoming buffer and then server can consider client a slow consumer and close connection with him (statistics obtained from nats server web interface tells so). In my case I use indefinite incoming buffer size and I thought that this can occur only if my consumer will totally run out of RAM but it still working and OS stat does not show big memory usage right now (but several hours have passed since connection close). Maybe NATS server has additional logic to detect slow consumers, because I suppose that nats.c did not drop any message because of indefinite incoming buffer size.
2) Does nats.c reconnects automatically if connection was closed because it was considered slow (I think the answer is no and agree with this behaviour, just want to know for sure)?

**Comment by kozlovic** [comment]
> Library documentation says that client will signal to server that it starts dropping messages because of insufficient space in incoming buffer and then server can consider client a slow consumer and close connection with him (statistics obtained from nats server web interface tells so)

Not sure how you saw that, please let me know and we will fix. I believe that I already referred to the FAQ about slow consumers at one point. Here is a copy for your convenience:
```
What is the SLOW CONSUMER error that I see in the server?

The server when sending data to a client (or route) connection sets a write deadline.
That is, if the socket write blocks for that amount of time, it will simply close the
connection.

This error occurs when the client (or other server) is not reading data fast enough
from the socket. As we have seen earlier, a client connection creates a thread 
whose job is to read data from the socket, parse it and move protocol or messages
to appropriate handlers.

So this is not really symptomatic of a message handler processing messages too
slowly, instead it is probably the result of resources issues (not enough CPU 
cycles to read from the socket, or not reading fast enough) or internal locking
contention that prevents the thread reading from the socket to read data fast
enough because it is blocked trying to acquire some lock.

What is the SLOW CONSUMER error in the client then?

This error, in contrast with the error reported by the server, has to do with the
disptaching of messages to the user callback. As explained, messages are 
moved from the connection's thread reading from the socket to the 
subscription's thread responsible for dispatching.

The subscription's internal queue as a default limited size. When the connection's
thread cannot add a message to that queue because it is full, it will drop the
message and if an error handler has been set, a message will be posted there.

For instance, having a message handler that takes too much time processing a
message is likely to cause a slow consumer client error if the incoming message
rate is high and/or the subscription pending limits are not big enough.

The natsSubscription_SetPendingLimits() API can be used to set the 
subscription's internal queue limits. Values of -1 for count and/or size means that
the corresponding metric will not be checked. Setting both to -1 mean that the
client library will queued all incoming messages, regardless at which speed they 
are dispatched, which could cause your application to use lots of memory.
```
As you can see, a SLOW CONSUMER from the server side means that the socket was not dequeued in a timely fashion.

> Does nats.c reconnects automatically if connection was closed because it was considered slow (I think the answer is no and agree with this behaviour, just want to know for sure)?

Again, when it is the server side detecting a client as a slow consumer, it means that a TCP write blocks for more than the write deadline (configured in the server, defaults to 2sec). When that happens it closes the client connection. The client library will react to a connection close and WILL try to reconnect (assuming that it is not configured to not reconnect).

**Comment by pananton** [comment]
Oh, sorry, I've missed the section regarding server-side issues. And I misunderstood documentation of NATS server regarding slow consumers. So can you please tell, whether the following is correct:
1) NATS slow consumer detected on client side does not cause connection close, only error callback is called.
2) Client-side slow consumer is not counted in server statistics ```varz``` endpoint (```slow_consumer``` field). 
3) NATS slow consumer detected on server side will cause connection close, but client which is configured to reconnect should then restore it's connection.

Btw, if client is configured to indefinetely reconnect to NATS server and I know that it did connect initially is there any well-known situation in which he can lost connection forever later (not taking into account OS/hardware-related errors)? My NATS cluster is still running, but it's statistics shows that connection number decreased by one and I supposed that happened because detected slow consumer was permanently disconnected - which is not correct accroding to your above message.

**Comment by kozlovic** [comment]
> NATS slow consumer detected on client side does not cause connection close, only error callback is called.

Correct.

> Client-side slow consumer is not counted in server statistics varz endpoint (slow_consumer field).

Correct.

> NATS slow consumer detected on server side will cause connection close, but client which is configured to reconnect should then restore it's connection.

Correct.

> My NATS cluster is still running, but it's statistics shows that connection number decreased by one and I supposed this happened because detected slow consumer was permanently disconnected - which is not correct accroding to your above message.

Check in which situations your app/lib is closing the NATS connection and try to see if that could be triggered by a disconnect that would happen during a slow consumer server-side.
Since you use monitoring, I would recommend that you check the state of the closed connections to have a better understanding of which connection was closed and the reason.
Here is the main link to the Connz endpoint: https://docs.nats.io/nats-server/configuration/monitoring#connection-information
Read the whole section, but here is a quick example on how to get the closed connections state:
```
Get closed connection information: http://<host>:<port>/connz?state=closed.
```

http://demo.nats.io:8222/connz?state=closed

**Comment by pananton** [comment]
Thanks a lot!

**Comment by pananton** [comment]
@kozlovic I've looked for closed connection reason and I see that my client performed a lot of reconnect attempts (after it was disconnected as slow consumer) and each connection was closed with reason "Client closed". Does this mean that it was client who closed connection and nats server was not responsible for connection close at all?

**Comment by kozlovic** [comment]
Are you sure you are not looking at other connections? For instance the publisher? Here is an example of running a server and a subscriber that is immediately put into sleep (ctrl+Z), then I start a publisher that publishes a lot of messages which causes the server to close the connection as a slow consumer. Once the publisher is done, check connz with closed state:
```
{
  "server_id": "NDJ4CJ547OSIN5MWNJPGS2GJH47DEZNOBNMMCHMQSZLVZJF2DOQLEJMX",
  "now": "2020-05-04T11:11:00.0087-06:00",
  "num_connections": 2,
  "total": 2,
  "offset": 0,
  "limit": 1024,
  "connections": [
    {
      "cid": 1,
      "ip": "127.0.0.1",
      "port": 53021,
      "start": "2020-05-04T11:10:49.184084-06:00",
      "last_activity": "2020-05-04T11:10:54.348895-06:00",
      "stop": "2020-05-04T11:10:56.352496-06:00",
      "reason": "Slow Consumer (Write Deadline)",
      "rtt": "521µs",
      "uptime": "7s",
      "idle": "2s",
      "pending_bytes": 66555,
      "in_msgs": 0,
      "out_msgs": 4403,
      "in_bytes": 0,
      "out_bytes": 563584,
      "subscriptions": 1,
      "name": "NATS Sample Subscriber",
      "lang": "go",
      "version": "1.9.2"
    },
    {
      "cid": 2,
      "ip": "127.0.0.1",
      "port": 53024,
      "start": "2020-05-04T11:10:54.347553-06:00",
      "last_activity": "2020-05-04T11:10:57.378863-06:00",
      "stop": "2020-05-04T11:10:57.378975-06:00",
      "reason": "Client Closed",
      "rtt": "569µs",
      "uptime": "3s",
      "idle": "0s",
      "pending_bytes": 0,
      "in_msgs": 10000000,
      "out_msgs": 0,
      "in_bytes": 1280000000,
      "out_bytes": 0,
      "subscriptions": 0,
      "name": "NATS Benchmark",
      "lang": "go",
      "version": "1.9.2"
    }
  ]
}
```
Then I resume the subscriber (foreground) and check the connections currently opened:
```
{
  "server_id": "NATTU22CZ5BC7P7KIYFPFEBC22IBGW3BCDZR5ZTD2QZMXA23W6YW7D7L",
  "now": "2020-05-04T11:15:27.860816-06:00",
  "num_connections": 1,
  "total": 1,
  "offset": 0,
  "limit": 1024,
  "connections": [
    {
      "cid": 3,
      "ip": "::1",
      "port": 53035,
      "start": "2020-05-04T11:15:20.28875-06:00",
      "last_activity": "2020-05-04T11:15:20.289052-06:00",
      "rtt": "707µs",
      "uptime": "7s",
      "idle": "7s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 1,
      "lang": "C",
      "version": "2.1.0"
    }
  ]
}
```

**Comment by pananton** [comment]
I was unable to find "Slow Consumer" reason in connz output. I suppose this is because that connection close was not detected by me for a while (several hours) and nats server documentation states (afaik) that it stores only N last errors (I think thats what "limit: 1024" in my connz output tells about). The only errors I can see are:
```
"connections": [
    {
      "cid": 11665,
      "ip": "10.0.0.159",
      "port": 60737,
      "start": "2020-04-29T13:51:21.653412893Z",
      "last_activity": "2020-04-29T13:51:21.672297406Z",
      "stop": "2020-04-29T13:51:21.682540837Z",
      "reason": "Client Closed",
      "rtt": "1.496058ms",
      "uptime": "0s",
      "idle": "0s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 1,
      "name": "GCM_CLIENT",
      "lang": "C",
      "version": "2.1.0"
    },
    {
      "cid": 11666,
      "ip": "10.0.0.159",
      "port": 60740,
      "start": "2020-04-29T13:51:21.744693459Z",
      "last_activity": "2020-04-29T13:51:21.763446133Z",
      "stop": "2020-04-29T13:51:21.773660494Z",
      "reason": "Client Closed",
      "rtt": "1.302194ms",
      "uptime": "0s",
      "idle": "0s",
      "pending_bytes": 0,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 1,
      "name": "GCM_CLIENT",
      "lang": "C",
      "version": "2.1.0"
    },

...

```

My client only creates 1 subscription and does not publish anything. ```connz``` output tells that subscription is created, but then connection is closed. Will look deeper into my code, your information already helped me a lot, thanks.

**Comment by pananton** [comment]
Can you please tell me whether there is any gaurantees that error cb (which receives client slow consumer notifications) will not be called after connection close cb? I perform some cleanup (which affects error cb closure argument) when connection is closed and if I will receive error cb after connection was closed my code can potentially crash.

**Comment by kozlovic** [comment]
@pananton Current connection callbacks such as error, disconnected, closed, etc.. are invoked serially in a separate thread. So if you get error then close, there is no chance to get the close before the error (for a given connection).

For full disclosure: some callbacks may be invoked in place when requiring user input in order to proceed, and in that case it would possibly happen out of order, but that is not the case for the type of callbacks you are referring to. For instance, we may introduce a callback that user can set to specify how long to wait during a reconnect. So technically the disconnect callback is posted first, but then the library would invoke the user callback to know how long to wait before reconnect. The invocation would be done in place, not posted to the async callback dispatcher. That callback may be invoked "before" the disconnect callback because the disconnect is invoked asynchronously. Hope that makes sense.

**Comment by pananton** [comment]
Thanks, Ivan. Everything is clear. But you wrote that

> if you get error then close, there is no chance to get the close before the error

Then my next question is whether erroc cb (set in natsOptions_SetErrorHandler) can be called after closed cb (set in natsOptions_SetClosedCb)? Documentation states that error cb

>... is used to process asynchronous errors encountered while processing inbound messages

In my code I free resources after I've received both closed cb and unsubscribe cb (remember I've asked you to make it public?) for all subscriptions. Now I need and error cb too and need to pass my object as a closure argument to it. So if I will receive error cb after all closed and unsubscribe callbacks then error cb will try to access already destroyed object. Documentation gives me a hope that this will never occur, because (as I mentioned above), error cb is called only when processing inbound message - and in my case I suppose no incoming messages exist (because I've already received closed cb and unsubscribe cb for all async subscriptions). Am I right?

**Comment by kozlovic** [comment]
Right, there is no chance for a given connection to have the error callback invoked before any other callbacks for this connection. If the connection is marked as closed, there is no chance to have an error condition later producing an error callback.
Again, a connection schedules invocations of its callback to a dedicated library thread that dispatch them. They are guaranteed to execute in order.
