### ISSUE TITLE
Is a Streaming equivalent of natsSubscription_SetOnComplete needed?

### ISSUE THREAD

**Issue by etrochim** [nats-io/nats.c#318]
Today I encountered a strange segfault in my NATS Streaming C++ application. Upon further investigation I found that it was because a message handler was using a closure object after I had already called `stanSubscription_Destroy` and deleted the closure object. After taking a very close look at stan/sub.c and the documentation it seems that I had incorrectly assumed that the closure object would not be used after the subscription object had been destroyed.

That investigation led me to this issue (https://github.com/nats-io/nats.c/issues/299) and this PR (https://github.com/nats-io/nats.c/pull/303) where `natsSubscription_SetOnComplete` was introduced to allow the closure to be deleted after nats.c was done with it. Is a similar function needed for the streaming API? Or is there a better way of knowing when to delete the closure object when using the streaming API?

**Comment by kozlovic** [comment]
@etrochim Sorry for the delay. No, there is not at the moment. If you can close the subscription from the message handler, then you won't have the problem. You could also do some synchronization between destroying of your closure and use in the message handler, but obviously that would require that the mutex lives for the duration of the app, not simply the subscription.
I will likely add the equivalent for the STAN API. Thanks!
