### ISSUE TITLE
Client slow consumer state detected but not notified (or with a delay)

### ISSUE THREAD

**Issue by bogossdu92** [nats-io/nats.c#327]
Client-side slow consumer state is detected in ``natsConn_processMsg``, but will only be notified the next time the function is called (or never if this was the last message to be received).
In that function, I see no obvious reason to do ``sc = sub->slowConsumer;`` instead of simply ``sc = true;`` ([now that the notification call to ``natsAsyncCb_PostErrHandler`` is done out of the subscription map lock](https://github.com/nats-io/nats.c/commit/60590f354c4fa444d685092015f5db6f7d971dd0). 

But this looks too easy to be true, and a seasoned ``nats.c`` developer should have a look.

**Comment by kozlovic** [comment]
@bogossdu92 Thank you for the report, having a look right now!
