### ISSUE TITLE
Observing almost immediate disconnect and close after a reconnect with STAN.

### ISSUE THREAD

**Issue by pbalash0v** [nats-io/nats.c#330]
Hello,
First off, thanks for all the hard work on this project. The statement in title of issue can be illustrated with following:
I augment code from examples/stan/sub.c like so:
```
static void
connectionLostCB(stanConnection *sc, const char *errTxt, void *closure)
{
    bool *connLost = (bool*) closure;

    printf("Connection lost, %s: %s\n", __func__, errTxt);
    //*connLost = true;
}

static void
nats_error_handler(natsConnection* nc, natsSubscription* subscription, natsStatus err, void* closure)
{
    printf("%s\n", __func__);
}

static void
nats_reconnected_handler(natsConnection* nc, void* closure)
{
    printf("%s\n", __func__);
}

static void
nats_disconnected_handler(natsConnection* nc, void* closure)
{
    printf("%s\n", __func__);
}

static void
nats_closed_handler(natsConnection* nc, void* closure)
{
    printf("%s\n", __func__);
}
```

And also, in main:
```
    s = natsOptions_SetClosedCB(opts, nats_closed_handler, NULL);

    if (NATS_OK == s)
        s = natsOptions_SetDisconnectedCB(opts, nats_disconnected_handler, NULL);

    if (NATS_OK == s)
        s = natsOptions_SetReconnectedCB(opts, nats_reconnected_handler, NULL);

    if (NATS_OK == s)
        s = natsOptions_SetErrorHandler(opts, nats_error_handler, NULL);
```

Then I:

-  launch nats-streaming-server
- launch modified sub example
- kill nats-streaming-server
- observe sub output
- restart nats-streaming-server
- observe sub output

That is what I got form sub output:
```
Receiving 1000000 messages from channel 'foo'
nats_disconnected_handler
nats_reconnected_handler
nats_disconnected_handler
nats_closed_handler
Connection lost, connectionLostCB: client has been replaced or is no longer registered
```

Question is why does my sub client gets almost instantly disconnected after a successful reconnect ? May be I'm missing some nats/stan concept and this is an expected behavior ? Is there some NATS (STAN) option I should set to prevent this ?

Thanks for your attention.

**Comment by kozlovic** [comment]
> First off, thanks for all the hard work on this project. 

Thanks for the compliment!

> Question is why does my sub client gets almost instantly disconnected after a successful reconnect ? May be I'm missing some nats/stan concept and this is an expected behavior ? Is there some NATS (STAN) option I should set to prevent this ?

I suspect that you are running the NATS Streaming server without persistent store (the default is MEMORY), so when it restarts, it does not have knowledge of this client. When the client sends the next PING with its connection ID, the server does not find it and returns an error.
Should you re-run the whole test with (re)starting the server this way: `nats-streaming-server -store file -dir <my datastore directory>` you should not have this issue.

**Comment by pbalash0v** [comment]
Thanks a lot for such a prompt and precise reply. That was exactly the issue on my side.
