### ISSUE TITLE
Stan functions not recogniced

### ISSUE THREAD

**Issue by 012345678987654321** [nats-io/nats.c#349]
Hi!

I've build the lastest version of nats (2.1) on my x86_64 ubuntu 20.04 system. Everything worked fine, expect some warnings due the build. But now I have the problem that all the stan functions are not recogniced by gcc/clion:

warning: implicit declaration of function ‘stanConnection_Connect’; did you mean ‘natsConnection_Connect’? [-Wimplicit-function-declaration]

Any idea what went wrong? Did i missed something? The commands I've used so far:

```
camke ..; make; sudo make install;
```

Thank you.

**Comment by kozlovic** [comment]
>  Everything worked fine, expect some warnings due the build

Well, what kind of warnings?

**Comment by kozlovic** [comment]
I could simply be that because the streaming definitions in nats.h are under `#if defined(NATS_HAS_STREAMING)` you would need to add this define in your IDE.

**Comment by 012345678987654321** [comment]
Hi!

These are the warnings I get:

```
/gitlab/test-server/nats/src/nats.c: In function ‘_cleanupThreadSSL’:
/gitlab/test-server/nats/src/nats.c:147:5: warning: ‘ERR_remove_thread_state’ is deprecated [-Wdeprecated-declarations]
  147 |     ERR_remove_thread_state(0);
      |     ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ssl.h:15,
                 from /gitlab/test-server/nats/src/natsp.h:24,
                 from /gitlab/test-server/nats/src/nats.c:14:
/usr/include/openssl/err.h:260:1: note: declared here
  260 | DEPRECATEDIN_1_1_0(void ERR_remove_thread_state(void *))
      | ^~~~~~~~~~~~~~~~~~
/gitlab/test-server/nats/src/nats.c: In function ‘_finalCleanup’:
/gitlab/test-server/nats/src/nats.c:161:9: warning: ‘ERR_remove_thread_state’ is deprecated [-Wdeprecated-declarations]
  161 |         ERR_remove_thread_state(0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ssl.h:15,
                 from /gitlab/test-server/nats/src/natsp.h:24,
                 from /gitlab/test-server/nats/src/nats.c:14:
/usr/include/openssl/err.h:260:1: note: declared here
  260 | DEPRECATEDIN_1_1_0(void ERR_remove_thread_state(void *))
      | ^~~~~~~~~~~~~~~~~~

/gitlab/test-server/nats/src/opts.c: In function ‘_createSSLCtx’:
/gitlab/test-server/nats/src/opts.c:280:9: warning: ‘TLSv1_2_client_method’ is deprecated [-Wdeprecated-declarations]
  280 |         ctx->ctx = SSL_CTX_new(TLSv1_2_client_method());
      |         ^~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ssl.h:15,
                 from /gitlab/test-server/nats/src/natsp.h:24,
                 from /gitlab/test-server/nats/src/opts.c:14:
/usr/include/openssl/ssl.h:1891:1: note: declared here
 1891 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void))
      | ^~~~~~~~~~~~~~~~~~

/gitlab/test-server/nats/src/nats.c: In function ‘_cleanupThreadSSL’:
/gitlab/test-server/nats/src/nats.c:147:5: warning: ‘ERR_remove_thread_state’ is deprecated [-Wdeprecated-declarations]
  147 |     ERR_remove_thread_state(0);
      |     ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ssl.h:15,
                 from /gitlab/test-server/nats/src/natsp.h:24,
                 from /gitlab/test-server/nats/src/nats.c:14:
/usr/include/openssl/err.h:260:1: note: declared here
  260 | DEPRECATEDIN_1_1_0(void ERR_remove_thread_state(void *))
      | ^~~~~~~~~~~~~~~~~~
/gitlab/test-server/nats/src/nats.c: In function ‘_finalCleanup’:
/gitlab/test-server/nats/src/nats.c:161:9: warning: ‘ERR_remove_thread_state’ is deprecated [-Wdeprecated-declarations]
  161 |         ERR_remove_thread_state(0);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ssl.h:15,
                 from /gitlab/test-server/nats/src/natsp.h:24,
                 from /gitlab/test-server/nats/src/nats.c:14:
/usr/include/openssl/err.h:260:1: note: declared here
  260 | DEPRECATEDIN_1_1_0(void ERR_remove_thread_state(void *))
      | ^~~~~~~~~~~~~~~~~~

/gitlab/test-server/nats/src/opts.c: In function ‘_createSSLCtx’:
/gitlab/test-server/nats/src/opts.c:280:9: warning: ‘TLSv1_2_client_method’ is deprecated [-Wdeprecated-declarations]
  280 |         ctx->ctx = SSL_CTX_new(TLSv1_2_client_method());
      |         ^~~
In file included from /usr/include/openssl/e_os2.h:13,
                 from /usr/include/openssl/ssl.h:15,
                 from /gitlab/test-server/nats/src/natsp.h:24,
                 from /gitlab/test-server/nats/src/opts.c:14:
/usr/include/openssl/ssl.h:1891:1: note: declared here
 1891 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void))
      | ^~~~~~~~~~~~~~~~~~
```

How can I add the define to CLion (not IntelliJ, sry)?

**Comment by kozlovic** [comment]
You seem to have OpenSSL 1.1+ installed, so you should build with `NATS_BUILD_TLS_USE_OPENSSL_1_1_API` option:
```
cmake .. -DNATS_BUILD_TLS_USE_OPENSSL_1_1_API=ON
```
See https://github.com/nats-io/nats.c#tls-support

> How can I add the define to CLion (not IntelliJ, sry)?

https://stackoverflow.com/questions/57022145/how-to-define-preprocessor-definition-for-each-configuration-in-clion

**Comment by kozlovic** [comment]
Or maybe this: https://youtrack.jetbrains.com/issue/CPP-166

Regardless, this is something you should bring up with CLion maintainers. Sorry I could not be of further help.

**Comment by 012345678987654321** [comment]
Solved it. I had to add #define NATS_HAS_STREAMING directly to my code. But I was to tired to notice that I had to add it BEFORE I include the nats.h and not after. :D

But... is there a reason why the stan methods are behind NATS_HAS_STREAMING?

**Comment by kozlovic** [comment]
> Solved it. I had to add #define NATS_HAS_STREAMING directly to my code

I don't think this is the proper way. Each C/C++ IDE should have a configuration section to allow users to add preprocessor definitions. For instance I am using VSCode with a C/C++ extension, and there is an "C/C++: Edit Configuration (UI)" command that allows me to specify those.

Hardcoding these compilers preprocessor defines in your code is wrong in my opinion.

> But I was to tired to notice that I had to add it BEFORE I include the nats.h and not after. :D But... is there a reason why the stan methods are behind NATS_HAS_STREAMING?

Yes, because the library can be compiled without Streaming support. In this case, anything related to streaming should be compiled out. You can't have the public nats.h contains prototype functions that would not be implemented.

**Comment by Wotzhs** [comment]
Was about to make the same post as OP, but luckily I looked hard enough to have found this.

I am not using any IDE but here's how I got it to work without including that `#define NATS_HAS_STREAMING true` macro in my code, during compilation, simply include the `-DNATS_HAS_STREAMING=true`, e.g.:

```
g++ -std=c++17 -DNATS_HAS_STREAMING=true main.cpp ... 
```

**Comment by kozlovic** [comment]
Yes, this is what CMake does.
