### ISSUE TITLE
RPATHs disabled on OSX

### ISSUE THREAD

**Issue by ravidavi** [nats-io/nats.c#384]
Hi all,

It seems like RPATHs are explicitly disabled on OSX:
`CMakeLists.txt Line 170:     set(CMAKE_MACOSX_RPATH OFF)`

This makes it very difficult to use nats.c as part of another project on OSX, and makes it impossible to do so when the other project is Python based. This is because OSX System Integrity Protection (SIP) disables the use of DYLD_LIBRARY_PATH on Python and other executables contained in system locations, which makes it impossible for a Python-based project to load any shared libs that in turn load nats. This is a common use-case for Python interface libraries created using SWIG.

Besides, RPATHs are integral to properly designing relocatable apps on modern OSX, so CMAKE_MACOSX_RPATH should be left to the user and not explicitly set inside CMakeLists.txt.

I recommend removing that line and restoring the user's ability to set CMAKE_MACOSX_RPATH.

Thank you!
Ravi

**Comment by kozlovic** [comment]
Thank you for the feedback. When I don't set this, I keep getting this annoying warning:
```
 cmake ..
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   nats

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/ivan/dev/cnats/build
```
I can set it to ON and it works fine, but honestly would not mind not setting if I can get rid of the warning.

**Comment by ravidavi** [comment]
You're right, setting it to ON is perfectly legitimate as cmake docs indicate.

https://cmake.org/cmake/help/v3.19/prop_tgt/MACOSX_RPATH.html#prop_tgt:MACOSX_RPATH

So if you are ok with it, please set CMAKE_MACOSX_RPATH to ON.

Thanks,
Ravi
