### ISSUE TITLE
Expose Client Ip/Port From Socket

### ISSUE THREAD

**Issue by samc1213** [nats-io/nats.c#402]
I would love to have observability into each `natsConnection`'s Ip and Port. I am aware of `natsConnection_GetClientIP`:

https://github.com/nats-io/nats.c/blob/6b6e4004975f2e35499d397c422ba61b9a6f5717/src/conn.c#L4131

but this IP comes from the streaming server itself. It also lacks a port number. As part of some end-to-end testing, I am working on simulating network issues in the connection from the NATS client to the server. However, I need observability in code into what client Ip/Port I am using (I have multiple NATS connections from the same host, so I need the information in the client API itself).

Does this exists already? It seems like it would require a code change.

If so, wouldn't it be possible to put something into the connection code itself to retrieve the Ip and Port client-side? Something like calling `getsockname` on the file descriptor here:

https://github.com/nats-io/nats.c/blob/dc6ce2c9d4722b5782de19eeece1e49083ce76fa/src/comsock.c#L207-L230

**Comment by kozlovic** [comment]
@samc1213 Check to see if #403 would work for you. Thanks!

**Comment by samc1213** [comment]
@kozlovic Wow thank you for the quick response and PR! I'm just bummed I didn't get a chance to contribute some code! I'm taking a look at your changes but it looks like it's exactly what I'd want. Thanks for all your work on this project, been a pleasure to use so far
