### ISSUE TITLE
Wrong Callback being Called

### ISSUE THREAD

**Issue by sonofdays** [nats-io/nats.c#407]
Considering this gtest example...

```
    common::cnatsClient nc(serverAddress);

    EXPECT_EQ(NATS_OK, nc.setupNATSConnection());
    std::vector<std::string> mainSubjects = {"cmd.X.*", "cmd.Y.*"};
    EXPECT_EQ(NATS_OK, nc.setMainSubscriptions(mainSubjects));
    std::vector<std::string> libSubjects = {"libMsg"};
    EXPECT_EQ(NATS_OK, nc.setLibrarySubscriptions(libSubjects));

    int timeout = 500;
    std::string subject, rcvdMessage;

    EXPECT_EQ(NATS_OK, nc.publishMessage("libMsg", "salad"));
    EXPECT_EQ(NATS_OK, nc.getLibraryMessage(subject, rcvdMessage, timeout));

    EXPECT_EQ(NATS_OK, nc.publishMessage("cmd.X.shutdown", "now"));
    EXPECT_EQ(NATS_OK, nc.getMainMessage(subject, rcvdMessage, timeout)); // FAILING, timeout
```
The main point is that I register different callback functions between "main" messages and "library" messages.  For some reason, whatever callback is used in the last natsConnection_Subscribe(...) call is the callback used when any message is delivered.

The result of this test is that the last line fails due to a timeout on trying to read a received message from a private "library" queue that is never populated, since it went to the "main" queue.  Each queue is populated in the respective callback.  If the order of the sending/receiving is switched, the "main" message still times out.  If the order of the subscriptions is switched, it is still the first-subscribed that later fails.

**Comment by kozlovic** [comment]
You would need to show a bit more how you setup your subscriptions.
Here is a modification of the provided async subscription in `getstarted/asyncsub.c`:
```
diff --git a/examples/getstarted/asyncsub.c b/examples/getstarted/asyncsub.c
index 29b1aa4..b5f7be2 100644
--- a/examples/getstarted/asyncsub.c
+++ b/examples/getstarted/asyncsub.c
@@ -16,6 +16,7 @@
 static void
 onMsg(natsConnection *nc, natsSubscription *sub, natsMsg *msg, void *closure)
 {
+    printf("in onMsg1\n");
     printf("Received msg: %s - %.*s\n",
            natsMsg_GetSubject(msg),
            natsMsg_GetDataLength(msg),
@@ -25,7 +26,20 @@ onMsg(natsConnection *nc, natsSubscription *sub, natsMsg *msg, void *closure)
     natsMsg_Destroy(msg);
 
     // Notify the main thread that we are done.
-    *(bool *)(closure) = true;
+    // *(bool *)(closure) = true;
+}
+
+static void
+onMsg2(natsConnection *nc, natsSubscription *sub, natsMsg *msg, void *closure)
+{
+    printf("in onMsg2\n");
+
+    printf("Received msg: %s - %.*s\n",
+           natsMsg_GetSubject(msg),
+           natsMsg_GetDataLength(msg),
+           natsMsg_GetData(msg));
+
+    natsMsg_Destroy(msg);
 }
 
 int main(int argc, char **argv)
@@ -47,6 +61,9 @@ int main(int argc, char **argv)
         // You can pass a closure as the last argument.
         s = natsConnection_Subscribe(&sub, conn, "foo", onMsg, (void*) &done);
     }
+    if (s == NATS_OK)
+        s = natsConnection_Subscribe(&sub, conn, "other.subject", onMsg2, NULL);
+
     if (s == NATS_OK)
     {
         for (;!done;) {
```
Then I publish a message on "foo", and a message on "other.subject". I get the proper callbacks:
```
$ examples/getstarted/asyncsub 
Listening on subject 'foo'
in onMsg1
Received msg: foo - messageOnFoo
in onMsg2
Received msg: other.subject - messageOnOtherSubject
```
Note that if you specify the same callback (say here if I were to pass `onMsg`) to both subscriptions, then obviously the same callback would be invoked, but subject/content would still be of the correct message:
```
Listening on subject 'foo'
in onMsg1
Received msg: foo - messageOnFoo
in onMsg1
Received msg: other.subject - messageOnOtherSubject
```
But sharing the same callback can be dangerous because code can possibly execute concurrently, so you would have to make it threadsafe.

**Comment by sonofdays** [comment]
Thank you for the quick sanity check.  Likely not related, but I am using non-static C++ member callbacks through the method detailed at https://stackoverflow.com/a/29817048/2725742 and each work individually.

Not much help without more detailed code, but I modified the test to subscribe to two subjects each and print somewhat verbosely.  The one attempt to read a "main" message fails still, as all messages go to the "library" callback.

Registering cmd.X.* to onMainMsg
Registering cmd.Y.* to onMainMsg
Registering libtest1 to onLibraryMsg
Registering libtest2 to onLibraryMsg
Got cmd.X.shutdown, push to m_semLibrary in onLibraryMsg
Got cmd.Y.startup, push to m_semLibrary in onLibraryMsg
../test/gtest.cpp:48: Failure
      Expected: NATS_OK
      Which is: 0
To be equal to: nc.getMainMessage(subject, rcvdMessage, timeout)
      Which is: 1
Got libtest1, push to m_semLibrary in onLibraryMsg
Got libtest2, push to m_semLibrary in onLibraryMsg

Hopefully I am able to identify whatever the issue is.  I may be back.

**Comment by sonofdays** [comment]
I have found that trying to define two non-static callbacks within the same scope/executable, using the linked method, causes the first callback to be overridden by the second so not at NATS.io issue.  Greatly appreciate the sanity check, @kozlovic.
