### ISSUE TITLE
Is there any support of JetStream?

### ISSUE THREAD

**Issue by navrocky** [nats-io/nats.c#438]
I see in a documentation only one reference to JetStream (its here https://github.com/nats-io/nats.c#jetstream).

What is the status of JetStream support?

**Comment by kozlovic** [comment]
It's in the works in this branch: https://github.com/nats-io/nats.c/tree/js
Note that the branch is updated from time to time and there may be breaking changes until the feature is ready for a PR.

You are encouraged to have a look if interested and report feedback, but please note that the code base may change (I refrain from doing git force push'es but still have breaking changes from time to time).

**Comment by kozlovic** [comment]
Closed by #446. Releasing v3.0.0 tonight.
