### ISSUE TITLE
Why is it not possible to use one thread for all subscribers (nats_SetMessageDeliveryPoolSize(1))?

### ISSUE THREAD

**Issue by atokarev** [nats-io/nats.c#439]
I want to use single thread mode for all subscribers with additional options: nats_SetMessageDeliveryPoolSize(1) and natsOptions_UseGlobalMessageDelivery(TRUE).
But it is not possible because by implementation minimum allowed threads num is 2.

In function nats_Open() maximum workers pool size is set to 2:
...
gLib.dlvWorkers.maxSize = 2;
gLib.dlvWorkers.workers = NATS_CALLOC(gLib.dlvWorkers.maxSize, sizeof(natsMsgDlvWorker*));
...

With function nats_SetMessageDeliveryPoolSize() we unable to reduce threads number (mnimum allowed threads count is 2):

...
natsStatus
nats_SetMessageDeliveryPoolSize(int max)
...
    // Do not error on max < workers->maxSize in case we allow shrinking
    // the pool in the future.
    if (max > workers->maxSize)
    {
...

I didn't find any way to change this behavior.

I want to clarify why predefined max threads count = 2 is used and why we can't use single thread? 

Thank you.

**Comment by kozlovic** [comment]
@atokarev I don't recall if there was a specific reason why I set the minimum to 1. I know that I did not implement the shrinking of a pool, so that explains the check here that does not do anything if the new max is below current max size.
I will review and see if we could make the new default 1 and see if I can implement shrinking of the pool. I will update the ticket later.

**Comment by kozlovic** [comment]
@atokarev I have just changed the default size to 1 (down from 2). I have not implemented shrinking because there may be subscriptions using some of the workers that would have to be removed for the new size, and that is not that straight forward.

**Comment by atokarev** [comment]
Thank you very much for quick reply!
I checked it, now it works as expected.
When will the new version be released (with this fix)?

**Comment by kozlovic** [comment]
@atokarev I may do a release later today.

**Comment by atokarev** [comment]
> @atokarev I may do a release later today.

Great, it will be awesome!

**Comment by kozlovic** [comment]
Here it is: https://github.com/nats-io/nats.c/releases/tag/v2.6.0
