### ISSUE TITLE
CMAKE_BUILD_TYPE is always overwritten

### ISSUE THREAD

**Issue by marascio** [nats-io/nats.c#450]
The top level `CMakeLists.txt` will always overwrite `CMAKE_BUILD_TYPE`, setting it to `Release`, or whatever has been specified in `NATS_BUILD_TYPE`. I'm not sure why `NATS_BUILD_TYPE` is used to drive the build type selection, but in the cases where nats is being included via `add_subdirectory()` this behavior is undesirable.

Preferably, `CMAKE_BUILD_TYPE` would be set only if it wasn't already set. This might have been the intention, but by using variable type `INTERNAL` it is being force set.

**Comment by kozlovic** [comment]
Close by #451
