### ISSUE TITLE
where and when the nats_EXPORTS and nats_IMPORTS variable definitions are defined ?

### ISSUE THREAD

**Issue by Daniel-Huff** [nats-io/nats.c#452]
This is a piece of code from the nats.h file.
I would like to know where and when the nats_EXPORTS and nats_IMPORTS variable definitions are defined .
But I can't find them. Can anyone help me?  

#if defined(_WIN32)
  #include <winsock2.h>
  #if defined(nats_EXPORTS)
    #define NATS_EXTERN __declspec(dllexport)
  #elif defined(nats_IMPORTS)
    #define NATS_EXTERN __declspec(dllimport)
  #else
    #define NATS_EXTERN
  #endif

**Comment by kozlovic** [comment]
In CMakeLists.txt, you can see this command:
```
install(TARGETS nats EXPORT ...
```
this is setting the `nats_EXPORTS` definition. This means that we are building a library so we want to export the symbols.

However, for applications that use the nats.h, such the examples, the header should instruct that those APIs are imported, not exported. So you will find in the examples and some tests that link against the DLL, that we use `add_definitions(-Dnats_IMPORTS)`, which adds the `nats_IMPORTS` definition.
