### ISSUE TITLE
libnats RPM packaging

### ISSUE THREAD

**Issue by sergey-safarov** [nats-io/nats.c#483]
I have prepared SPEC file for libnats packaging.
Could you make make libnats package

[libnats.spec](https://github.com/sergey-safarov/kamailio-builder/blob/master/rpm_extra_specs/libnats.spec)

**Comment by kozlovic** [comment]
I am sorry, I am not familiar at all with RPM packaging, so if you could let me know what needs to be done, I would appreciate it. Otherwise, I will have to research and I am quite busy at the moment, so that would not be a high priority.

**Comment by sergey-safarov** [comment]
Could you show the folder where you plan to store packaging files?
I will create PR with instructions on how to manually build rpm packages.

If you use docker, I can create instructions or bash (Makefile) that will allow building rpm package using docker.

**Comment by sergey-safarov** [comment]
> I release the library just with sources. Users build themselves. I actually provide CMakeLists.txt files (using CMake) so I don't have to learn or deal with platform specific build environments

So I will write only readme file.

**Comment by philpennock** [comment]
I last touched a `.spec` file in 2012, so I can't give a meaningful review, but this looks sane.  The bigger issue will be arranging for automated builds and packaging, so that we don't require macOS developers to have rpm installed locally.  Normally, I use something like `nfpm` for cross-platform packaging.

At present, we just do source-code releases.  I don't think we're willing to start binary library releases at this time?

**Comment by sergey-safarov** [comment]
Thanks for the answer.
You can also place to repo spec file and do not build any RPM package binaries.
Users can build packages by themselves.
I can update the README file with two strings on how to build the package on RPM-based dist.

**Comment by kozlovic** [comment]
@sergey-safarov Yes, as we mentioned we release only the source. If you want to have the `.spec` file included and update the README, I would recommend that you submit a PR for that. Thanks!

**Comment by sergey-safarov** [comment]
Closing this as relevant PR created.
