### ISSUE TITLE
 subject wildcard ">"  does not work

### ISSUE THREAD

**Issue by BryceCao** [nats-io/nats.c#502]
Firstly,we has a durable stream with a subject "test.user", "nats-js-sub -subj test.*  -stream ...     -print   -s ..." can consume events normally,but "nats-js-sub -subj test.>  -stream ...     -print   -s ..." cant consume any event. its likely because js_GetConsumerInfo() get filterSubject with "u003e" instead of ">" , cause “”subject ... does not match consumer filter subject ...".

**Comment by kozlovic** [comment]
@BryceCao I have a PR that addresses the issue specific to JSON decoding of unicodes, but, I want to make sure we are clear that if the stream captures only test.user, then creating a consumer with a filter subject on "test.>" is not failing, but the consumer will not receive messages sent on "test.bar".
Also the C client has not yet implemented the following check regarding subscription filter matching: https://github.com/nats-io/nats-architecture-and-design/issues/67
