### ISSUE TITLE
natsOptions_SetCertificatesChain does only accept RSA keys

### ISSUE THREAD

**Issue by thierryba** [nats-io/nats.c#526]
natsOptions_SetCertificatesChain only accept RSA keys. In a attempt at making things a bit safer, we are using EC keys.

The current workaround is to write those to files and load them with natsOptions_LoadCertificatesChain.

**Comment by kozlovic** [comment]
@thierryba Thank you for the report. I have replaced used of RSA-specific key API in this PR: https://github.com/nats-io/nats.c/pull/527. I wonder if you could have a chance to test that branch and tell me if that works for you? Thanks!

**Comment by thierryba** [comment]
@kozlovic Thank you for that patch. I was planning on writing a PR myself today.
I just tested it and it works beautifully.

**Comment by mcosta74** [comment]
Any ETA to have a release with this fix ?
