### ISSUE TITLE
C++: natsMsgList default constructor is a deleted function

### ISSUE THREAD

**Issue by simontherry** [nats-io/nats.c#545]
The following line of code fails to compile using VS2022 (Win SDK 8.1)

```cplusplus
natsMsgList list;
```
with error: 
natsMsgList::natsMsgList(void)': attempting to reference a deleted function

'natsMsgList::natsMsgList(void)': function was implicitly deleted because 'natsMsgList' has an uninitialized const-qualified data member 'natsMsgList::Count'

Any thoughts on how to fix this?

**Comment by kozlovic** [comment]
Can you modify src/nats.h and look for `natsMsgList` definition and try to replace with this:
```
typedef struct natsMsgList
{
        char            **Msgs;
#ifdef __cplusplus        
        const int       Count = 0;
#else
        const int       Count;
#endif

} natsMsgList;
```
Does that work? But do you have other compilation issues then? There are many other places where I define `const` fields in structures, so not sure to what extent this is a problem for C++

**Comment by simontherry** [comment]
I tried changing it according your suggestion. However now I have the following problem:

```cplusplus
     std::vector<std::shared_ptr<IMessage>> messages;
      natsMsgList list;
      jsErrCode jerr = JSBadRequestErr;
      auto s = natsSubscription_Fetch(&list, this->subscription_, count, max_wait_millis, &jerr);

      for (int i = 0; (s == NATS_OK) && (i < list.Count); i++)
      {
          messages.emplace_back(std::make_shared<NatsMessage>(list.Msgs[i], nullptr));
      }

      natsMsgList_Destroy(&list);
      return messages;
```

Exception thrown at 0x00007FFC9E05B431 (natsd.dll) in myapplication.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

See screenshot: https://imgur.com/a/OI5jyLD

**Comment by Kazmirchuk** [comment]
I've just hit the same problem with the same compiler. nats.h has 4 structs with "const int": natsMsgList, jsStreamStateSubjects, kvEntryList, kvKeysList. Attempting to use any of them results in the same error about a deleted function.

I'd really prefer to avoid patching nats.h, because I'm working on an open-source project and use cmake to clone nats.c from Github automatically.

TBH I guess "const" can be simply removed here, since you cast it away anyway in js.c :
```
*(int*)&(pending->Count) = count;
```

**Comment by Kazmirchuk** [comment]
I suppose, using `js_PublishAsyncGetPendingList+natsMsgList_Destroy` is mandatory whenever `js_PublishAsyncComplete` returns `NATS_TIMEOUT` in order to avoid a memory leak, right?

**Comment by kozlovic** [comment]
> TBH I guess "const" can be simply removed here, since you cast it away anyway in js.c 

Reason I made it a const was to prevent user to change that value (accidentally) and then the list destroy could cause a crash. That was probably overthinking it.
I could remove the `const` (for the upcoming v3.4.0), but not sure if that will break applications.

>  I suppose, using js_PublishAsyncGetPendingList+natsMsgList_Destroy is mandatory whenever js_PublishAsyncComplete returns NATS_TIMEOUT in order to avoid a memory leak, right?

Not necessarily. If the call times-out, it just means that there are still unack'ed messages at the time this function returns the timeout. But those messages may receive an ack right after and memory will be correctly free by the library. You could even call  `js_PublishAsyncComplete` again after the timeout if you wanted to.
But at some point, if there is doubt that there may still be messages that did not get an ack, then yes, you would have to get the list and destroy it.

**Comment by Kazmirchuk** [comment]
> not sure if that will break applications.
TBH I can't imagine a code snippet that would break if you remove "const"
I've checked with gcc 9.1.0, it complains as well (when compiling in the C++ mode):
```
uninitialized const member in struct natsMsgList
const int natsMsgList::Count should be initialized
```
So, I suppose, these functions never worked in C++. Well, all of them are relatively recent, all related to JetStream or KV store.
