### ISSUE TITLE
Jetstream: API for QueueSubscribeSync()

### ISSUE THREAD

**Issue by Ann-Geo** [nats-io/nats.c#548]
Does the C client for Jetstream support QueueSubscribeSync() ? I don't see an API like js_QueueSubscribeSync() in nats.h file.
But I do see Jetstream go client has an API listed as func (js *js) QueueSubscribeSync(subj .....). So a similar API is not available for Jetstream C client ?

**Comment by kozlovic** [comment]
You would use `js_SubscribeSync()` (https://nats-io.github.io/nats.c/group__js_sub_group.html#gabacb010031e535f9fb6e2167337e8adf) but use a `jsSubOptions` to set the queue name, something like that:
```
jsSubOptions so;

jsSubOptions_Init(&so);
so.Queue = "MyQueue";
s = js_SubscribeSync(&sub, js, "foo", NULL, &so, NULL);
```
