### ISSUE TITLE
close Realtek Gaming 2.5GbE Family Controller,nats server subject has been forever

### ISSUE THREAD

**Issue by FJSDS** [nats-io/nats.c#554]
I have disabled the network adapter，but the subject on server forever!!!. However the go client been deleted after a few seconds
![image](https://user-images.githubusercontent.com/10356979/178207367-38cf0336-1a6f-40ef-8861-16dbf2dcdbe8.png)

**Comment by FJSDS** [comment]
This causes the send message to time out after opening the network adapter

**Comment by kozlovic** [comment]
@FJSDS  I would need a bit more information to be able to help. Not sure what you mean by "nats server subject has been forever", but I think you mean that inspecting some NATS Server monitoring endpoint, you can see one of the subject that your application subscribes to? Which endpoint are you looking at? Did you try `/connz` and try to look for that specific connection? Do a refresh from time to time and see if the connection seem active.

The server would consider a connection close if it gets a notification from the TCP stack that the connection is closed, or when reaching the number of failed heartbeats.

**Comment by FJSDS** [comment]
sorry，I got my nats-server configuration wrong
