### ISSUE TITLE
natsStatus_GetText does not work with jsErrCode

### ISSUE THREAD

**Issue by Kazmirchuk** [nats-io/nats.c#566]
as it says in the title
probably I can get the textual representation like "JSAccountResourcesExceededErr" using C++17 features, but it would look nicer to have a properly formatted message, and also would work in pure C.

**Comment by kozlovic** [comment]
@Kazmirchuk The point of jsErrCode is that it is just that, a code. You can use NATS CLI tool to match the error to some text. Note that APIs that return a jsErrCode do also return an error that you can print if you want (nats_GetLastError() or nats_GetLastErrorStack() or nats_PrintLastErrorStack()).

Using NATS CLI tool, and looking up error say 10058:
```
$ nats errors lookup 10058
NATS Error Code: 10058

        Description: stream name already in use
          HTTP Code: 400
  Go Index Constant: JSStreamNameExistErr
```
