### ISSUE TITLE
unable to build c-nats client dependency protoc-c 

### ISSUE THREAD

**Issue by khurramshahzadavanza** [nats-io/nats.c#569]
unable to build c-nats client dependency protoc-c as "Protobuf_SRC_ROOT_FOLDER-NOTFOUND" error is always there. Protoc-c has no documentation for building it for windows cygwin based build don't have static library just dll file whereas cnats require protoc-c library in linker settings.

**Comment by kozlovic** [comment]
@khurramshahzadavanza You should look at instructions here: https://github.com/nats-io/nats.c#building-with-streaming

If you don't plan to use NATS Streaming, then instruct CMake to not build the streaming code and there will be no need for protobuf. If you need streaming, in the above instructions, go to the protobuf library link and follow instructions there to build that library.
