### ISSUE TITLE
js_DirectGetMsg return NATS_TIMEOUT

### ISSUE THREAD

**Issue by danakeydar** [nats-io/nats.c#575]
Hi,
I'm using JetStream and trying to use js_DirectGetMsg.
I have a stream 'Jobs' that was created with the flag AllowDirect=true.

The API call is '$JS.API.DIRECT.GET.Jobs' and i'm getting NATS_TIMEOUT error.

jsDirectGetMsgOptions getMsgOpts;
jsDirectGetMsgOptions_Init(&getMsgOpts);
getMsgOpts.Sequence = 3;

natsMsg* msg;
s = js_DirectGetMsg(&msg, js, "Jobs", &jsOpts, &getMsgOpts);

(I'm using the 'js','jsOpts' objects in other successful calls)
 
When running the "nats stream get Jobs 3" command in nats CLI I get the message.

Any help?

**Comment by kozlovic** [comment]
@danakeydar Would you please let me know which version of the server are you using? If a nightly or built from source, would you mind posting the commit rev number?

**Comment by danakeydar** [comment]
@kozlovic Sure,  I'm using the latest release version 2.8.4.

**Comment by kozlovic** [comment]
@danakeydar That explains it. This feature will be available only in the v2.9.0 release (that you can try from NATS Server repo main branch or from the nightlies). I will add that information in the js_DirectGetMsg() doc.
