### ISSUE TITLE
Jetstream doesn't work with SetNoEcho

### ISSUE THREAD

**Issue by YordanSlavov** [nats-io/nats.c#589]
Hello, I have the following situation,

1) NATS server running in docker with published ports 4222 and 8222 for clients and monitoring as well as -js flag so that jetstream is enabled.
2) A C++ wrapper class that implements NATS C client functionality. The wrapper is connecting to the server using the default natsOptions aside from setting noEcho to be true. 

Context for my use case:

Some sample executables for testing purposes where each has a C++ wrapper instance (that contains the necessary connection and jetstream context). Both will try to first add a stream (e.g. "stream1" is the name in the config) with a channel (e.g. "channel1") in the subjects part of the config, but only if said stream does NOT already exist. Then both bind a callback for messages coming from said channel of the stream. One of the executables' callback only logs to the standard line what it receives and only publishes one message at the beginning of execution, while the other takes whatever message comes, appends a "status: received" to it and publishes on **_the same channel_** from which the message came (and it itself is subscribed to). This setup ends up having a sort of "endless recursion" from the publishers receiving their own messages.

I have looked into using natsOptions_SetNoEcho to true, however, this impacts only Core NATS functionality from the looks if it. Sadly that's not enough for my use case.

My questions are as follows,

1) Is this intentional?
2) If it is, then how would you recommend I proceed when it comes to the above scenario? Make separate channels (one for posting and one for intercepting)? Or is the commonplace solution to use uuids in the messages?
3) If there is a way around this behavior that doesn't involve step 2) then what is that way?

**Comment by kozlovic** [comment]
@YordanSlavov I am not super clear on what you are trying to do, but current behavior you describe seem expected to me. If you create a JetStream consumer on a stream "S" that collects subjects "foo" and receive a message from that stream, call it message M1 and then publish to subject "foo" a message M2, then this message becomes part of the stream and will therefore be consumed by the consumer on the stream. That will indeed create an infinite loop.

If you could describe in a bit more detailed the outcome you expect, I may be able to help better, but yes, at first reading it looks like you would need different streams (or at least subjects in the stream).

**Comment by YordanSlavov** [comment]
@kozlovic I'm sorry if my explanation is poor, but yes your remark hits the nail on the head. That is the exact situation I am referencing.

The outcome I would except is for the consumer to realize if he is consuming his own message and ignore it. This is possible for Core NATS functionality, but not for jetsream. I can only imagine that there's a specific reasoning behind this and would very much appreciate clarification.
