### ISSUE TITLE
Question: Is it possible to guard against the asynchronous callbacks for reconnect, disconnect and closed

### ISSUE THREAD

**Issue by YordanSlavov** [nats-io/nats.c#609]
Hello, I have been looking at the documentation and so far it appears that the three callbacks regarding connection state of a nats client to a nats server are all asynchronous. I can only assume that means that in theory they could come in any order regardless of the _current_ state of the connection.

Would natsConnection_Status(natsConnection* nc) give me a valid current state for the connection? If the answer is no, then is there some other API that I could use?

**Comment by kozlovic** [comment]
> I can only assume that means that in theory they could come in any order regardless of the current state of the connection

To be clear, the callbacks will be in order of the events that arise, say: disconnected followed by reconnected, etc... However, they may happen at a time that does not correspond to the current state of the connection. That is, a connection may be disconnected and already reconnected when the first callback regarding the disconnected state fires.

Calling `natsConnection_Status()` will give you indeed the *current* status of the connection, which may not match the state for which the error callback is invoked. Again, in the case above, you may have the error callback invoked saying that the connection is disconnected, but calling natsConnection_Status() would maybe return that the connection is connected (or reconnecting, or closed, etc..).
