### ISSUE TITLE
Acking messages in queue subscribers

### ISSUE THREAD

**Issue by starline-glitch** [nats-io/nats.c#623]
I try to set up a few queue subscribers to a single JetStream subject, but I faced some problems for both async and sync queue subscriptions.

ASYNC

First of all, why does the jetstream server keep storing processed and automatically ack'ed messages? All 11 messages in the screenshot were successfully processed by the application, but they were not automatically deleted by the server (manual ack disabled)
![image](https://user-images.githubusercontent.com/83460570/212976397-a55480c5-2b5d-48e8-910d-7eb3dae743ab.png)

After that, I tried manual acks but I have not found any examples of manual acking management for queue subscribers. Tried to call **natsMsg_Ack** manually inside the callback, but it returns NATS_ILLEGAL_STATE. **natsMsg_getSequence** and **js_EraseMsg** functions also don't work.

**Comment by kozlovic** [comment]
I assume that you did not create the stream with the WorkQueue retention policy, which means that messages are not removed when acknowledged, they are removed when hitting the limits.

I would recommend that you review Streams and Consumers in following documentation: https://docs.nats.io/nats-concepts/jetstream/streams.

**Comment by starline-glitch** [comment]
![image](https://user-images.githubusercontent.com/83460570/212999857-40c620c8-d1ed-492b-83bc-9070cccf103e.png)

My app got the message "9" in the callback (manual ack disabled), after that I run 'nats stream report' once again, message was in the stream.

**Comment by kozlovic** [comment]
> And it's also strange, that there are 0 consumers, although I have 1 app being run.

That may be the problem. You indeed have a WorkQueue stream, so messages should be deleted when they are acknowledged, but I now wonder if you are creating a proper JetStream consumer.

Could you share code on how you are receiving those messages? A very basic example exists showing how to create a JS consumer: https://github.com/nats-io/nats.c/blob/main/examples/js-sub.c

**Comment by starline-glitch** [comment]
```
void workers::NatsStage::onMsg(natsConnection *nc, natsSubscription *sub, natsMsg *msg, void *closure)
{
    jsErrCode  error;
    natsStatus status;

    auto text = natsMsg_GetData(msg);
    std::cout << text << std::endl;

    natsMsg_Destroy(msg);

    // All funcs below return error
    /*natsStatus status = natsMsg_Ack(msg, &js_options);
    assert(status == NATS_OK);

    auto seq = natsMsg_GetSequence(msg);
    std::cout << seq << std::endl;

    status = natsMsg_Ack(msg, &js_options);
    assert(status == NATS_OK);
    status = js_EraseMsg(jetstream_ctx, "nodes", seq, &js_options, &error);
    assert(status == NATS_OK);*/
}



void workers::NatsStage::init() {
    natsStatus status;
    jsErrCode  error;
    std::string host = "nats://" + Config::getConfig().getField<std::string>("nats_nodes_host") + ":" \
                                 + std::to_string(Config::getConfig().getField<int>("nats_nodes_port"));


    status = natsConnection_ConnectTo(&connection, host.c_str());
    assert(status == NATS_OK);
    status = jsOptions_Init(&js_options);
    assert(status == NATS_OK);
    status = jsSubOptions_Init(&sub_options);
    assert(status == NATS_OK);

    sub_options.Stream           = "nodes";
    sub_options.ManualAck        = false;
    sub_options.Config.AckPolicy = js_AckNone;

    js_options.Wait = 5000;

    status = natsConnection_JetStream(&jetstream_ctx, connection, &js_options);
    assert(status == NATS_OK);
    status = natsConnection_QueueSubscribe(&subscription, connection, "nodes_subject", "workers", onMsg, NULL);
    assert(status == NATS_OK);
}
```

Commented section in the onMsg describes how I tested manual acking and message deletion with ManualAck Policy (all failed)

**Comment by kozlovic** [comment]
As you can see, you have created a JetStream context but are not using it. You simply created a regular NATS queue subscription that happens to receive messages that are produced, but this is not a JetStream consumer, so this is why ack'ing and getting message sequence fails, because these are not JetStream messages.

Like I wrote in my previous comment, have a look at https://github.com/nats-io/nats.c/blob/main/examples/js-sub.c. I would recommend that you use `js_PullSubscribe()`, which matches better the notion of doing "multiple" consumers (as queue consumers) on a WorkQueue stream.

**Comment by kozlovic** [comment]
PS: I assume that you did not invoke natsMsg_Destroy() in the callback before invoking functions on that message. The reason the calls failed is described in previous comment (not a JetStream consumer), but still, keep in mind not to destroy a message and then invoke functions on that message.

**Comment by starline-glitch** [comment]
Do you mean using `js_PullSubscribe()` instead of `natsConnection_QueueSubscribe`? I tried that, but in this case I can't connect two or more subscribers to one subject. A few subscribers per one subject is that I need.

**Comment by kozlovic** [comment]
Sorry. Assuming that you do not yet have a JetStream consumer, you should probably create a durable JS consumer with a deliver group (you can use the NATS CLI or use the C API - see http://nats-io.github.io/nats.c/structjs_consumer_config.html and js_AddConsumer). Then, your application should call js_Subscribe() with jsSubOptions specifying `Consumer` as the durable name and `Queue` as the deliver group specified when creating the JS consumer.

**Comment by starline-glitch** [comment]
Well, I found just now this article [https://natsbyexample.com/examples/jetstream/workqueue-stream/crystal](url), which says ** this retention type allows for a set of consumers that have _non-overlapping_ interest on subjects**

My goal is to replace RMQ with JetStream Nats (temporarily). RMQ allows you make multiple consumers connected to the similar routing key without replication each message for each consumer. According to the article it's impossible for WorkQueue Nats.

**Comment by kozlovic** [comment]
Check my previous comment. You can create a durable queue JS consumer, then your app can create as many queue subscribers on that consumer. The messages will be randomly distributed to those queue subscriptions.

**Comment by starline-glitch** [comment]
Yes, it seems to be working, thank you.

As far as I understand, a durable JS consumer with a delivery group supports only _push_-consumers. In this case, `natsSubscription_Fetch` call is unavailable (it always returns NATS_INVALID_SUBSCRIPTION). There are no any options to use `natsSubscription_Fetch` with push-subscription, are there?

**Comment by kozlovic** [comment]
@starline-glitch This function is for pull subscribers, which we saw is not the best choice actually for WorkQueue streams (unless you have non overlapping subjects and are fine with one pull consumer per filtered subject). You can still use the js_Subscribe() with a queue name and provide a callback, or use the js_SubscribeSync() if you prefer (you have then to call natsSubscription_NextMsg()).
