### ISSUE TITLE
natsSubscription_Fetch not respecting timeout

### ISSUE THREAD

**Issue by kino71** [nats-io/nats.c#631]
While running "nats con info" on a pull consumer, we noticed that "Waiting Pulls" was unexpectedly 2, while there was only one process pulling / fetching.
Further digging showed that after a while (sometime 30 minutes, sometime more), "waiting pulls" becomes 2 in our C++ applications compiled with 3.5.0 and 3.6.0 (apparently not with 3.3.0). Server version is latest 2.9.11

We added logging on our application and it turned out that, after a while, natsSubscription_Fetch returns every other call well below timeout (no message to deliver) .
We have a minimal example available here : https://gist.github.com/julio77it/d9e7134328c0ed84b6acaaf01aa519ad
running it:

> stream_consumer -s nats://mercury_test:mercury@vxr-dev-nats03:4222 --str QSLM --con LMTEMP --subj LM.TEMP.ORDER.QS --timeout 5000

Stream and consumer are R3 (don't know if it makes a difference)

This subscription shows the behavior

nats sub "\$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP" 

```
08:02:00 Subscribing on $JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP 
[#1] Received on "$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP" with reply "_INBOX.SJXVUH3BFDOD5X3DASWU7N"
{"batch":1,"expires":4990000000}
[#2] Received on "$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP" with reply "_INBOX.SJXVUH3BFDOD5X3DASWU7N"
{"batch":1,"expires":4990000000}
```

messages #1 e #2 are very close apart, instead of 5 secs. Next request (#3) respect 5 secs timeout.

I raised log level on cluster node, it shows the behavior even better:
(grepping "TEMP")

```
[2000652] 2023/02/01 08:03:41.277135 [TRC] 10.126.5.22:37012 - cid:1929 - "v3.6.0:C:Consumer on QSLM:LMTEMP:LM.TEMP.ORDER.QS" - ->> [HMSG _INBOX.SJXVUH3BFDOD5X3DASWU7N 2 81 81]
[2000652] 2023/02/01 08:03:41.278087 [TRC] 10.126.5.22:37012 - cid:1929 - "v3.6.0:C:Consumer on QSLM:LMTEMP:LM.TEMP.ORDER.QS" - <<- [PUB $JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP _INBOX.SJXVUH3BFDOD5X3DASWU7N 32]
[2000652] 2023/02/01 08:03:41.278129 [TRC] 10.126.5.22:37012 - cid:1929 - "v3.6.0:C:Consumer on QSLM:LMTEMP:LM.TEMP.ORDER.QS" - <<- MSG_PAYLOAD: ["{\"batch\":1,\"expires\":4990000000}"]
[2000652] 2023/02/01 08:03:41.278137 [TRC] 10.126.5.22:37012 - cid:1929 - "v3.6.0:C:Consumer on QSLM:LMTEMP:LM.TEMP.ORDER.QS" - ->> [OK]
[2000652] 2023/02/01 08:03:41.278155 [TRC] 10.126.5.25:6222 - rid:1290 - ->> [RMSG mercury_test $JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP _INBOX.SJXVUH3BFDOD5X3DASWU7N 32]
[2000652] 2023/02/01 08:03:41.473837 [TRC] 10.126.5.22:37012 - cid:1929 - "v3.6.0:C:Consumer on QSLM:LMTEMP:LM.TEMP.ORDER.QS" - ->> [HMSG _INBOX.SJXVUH3BFDOD5X3DASWU7N 2 81 81]
[2000652] 2023/02/01 08:03:41.475087 [TRC] 10.126.5.22:37012 - cid:1929 - "v3.6.0:C:Consumer on QSLM:LMTEMP:LM.TEMP.ORDER.QS" - <<- [PUB $JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP _INBOX.SJXVUH3BFDOD5X3DASWU7N 32]
[2000652] 2023/02/01 08:03:41.475130 [TRC] 10.126.5.22:37012 - cid:1929 - "v3.6.0:C:Consumer on QSLM:LMTEMP:LM.TEMP.ORDER.QS" - <<- MSG_PAYLOAD: ["{\"batch\":1,\"expires\":4990000000}"]
[2000652] 2023/02/01 08:03:41.475136 [TRC] 10.126.5.22:37012 - cid:1929 - "v3.6.0:C:Consumer on QSLM:LMTEMP:LM.TEMP.ORDER.QS" - ->> [OK]
[2000652] 2023/02/01 08:03:41.475153 [TRC] 10.126.5.25:6222 - rid:1290 - ->> [RMSG mercury_test $JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP _INBOX.SJXVUH3BFDOD5X3DASWU7N 32]
```

**Comment by kino71** [comment]
Might be useful nats server reply to fetch 

```
09:30:02 Subscribing on _INBOX.SJXVUH3BFDOD5X3DASWU7N 
[#1] Received on "_INBOX.SJXVUH3BFDOD5X3DASWU7N"
Nats-Pending-Messages: 1
Nats-Pending-Bytes: 0
Status: 408
Description: Request Timeout



[#2] Received on "_INBOX.SJXVUH3BFDOD5X3DASWU7N"
Status: 408
Description: Request Timeout
Nats-Pending-Messages: 1
Nats-Pending-Bytes: 0
```

**Comment by kozlovic** [comment]
Thank you for the report. I find strange that the `Nats-Pending-Messages` is > 0, but the `Nats-Pending-Bytes` is 0. Maybe something is wrong with this consumer. Have you run a `nats c info` on that consumer and what would be the output?

**Comment by kino71** [comment]
Information for Consumer QSLM > LMTEMP created 2023-01-18T12:13:33+01:00

Configuration:

        Durable Name: LMTEMP
           Pull Mode: true
      Filter Subject: LM.TEMP.ORDER.QS
      Deliver Policy: All
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
  Maximum Deliveries: 10
     Max Ack Pending: 5
   Max Waiting Pulls: 512

Cluster Information:

                Name: stage
              Leader: vxr-dev-nats01
             Replica: vxr-dev-nats02, current, seen 0.58s ago
             Replica: vxr-dev-nats03, current, seen 0.58s ago

State:

   Last Delivered Message: Consumer sequence: 76 Stream sequence: 6,655 Last delivery: 8h0m44s ago
     Acknowledgment floor: Consumer sequence: 76 Stream sequence: 6,648 Last Ack: 8h0m44s ago
         Outstanding Acks: 0 out of maximum 5
     Redelivered Messages: 0
     Unprocessed Messages: 0
            Waiting Pulls: 2 of maximum 512

**Comment by kino71** [comment]
I have the same behavior in production (hence a different cluster):

17:53:46 Subscribing on _INBOX.AQNISGTOCQ66EK30TJFXHP 
[#1] Received on "_INBOX.AQNISGTOCQ66EK30TJFXHP"
Status: 408
Description: Request Timeout
Nats-Pending-Messages: 1
Nats-Pending-Bytes: 0



[#2] Received on "_INBOX.AQNISGTOCQ66EK30TJFXHP"
Description: Request Timeout
Nats-Pending-Messages: 1
Nats-Pending-Bytes: 0
Status: 408

**Comment by kozlovic** [comment]
The fact that the client receives an actual response (but with a shorter timeout than given) from the server is concerning. Could you try to stop your C application and do a consumer info and make sure that the "Waiting pulls" count goes to 0?

Could you let me know how/where do you print the above "Description/Nats-Pending..."? I want to make sure that this is really the result of a protocol message received from the server.

**Comment by kozlovic** [comment]
Also, could you send an output of "nats s info" for this consumer's stream?

**Comment by kino71** [comment]
>Also, could you send an output of "nats s info" for this consumer's stream?

Information for Stream QSLM created 2022-05-10 16:48:33

             Subjects: LM.*.*.QS
             Replicas: 3
              Storage: File

Options:

            Retention: Interest
     Acknowledgements: true
       Discard Policy: Old
     Duplicate Window: 2m0s
           Direct Get: true
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: stage
               Leader: vxr-dev-nats01
              Replica: vxr-dev-nats02, current, seen 0.76s ago
              Replica: vxr-dev-nats03, current, seen 0.76s ago

State:

             Messages: 5,958
                Bytes: 13 MiB
             FirstSeq: 616 @ 2022-12-09T20:50:20 UTC
              LastSeq: 6,655 @ 2023-02-01T14:03:37 UTC
     Deleted Messages: 82
     Active Consumers: 75
   Number of Subjects: 27

**Comment by kino71** [comment]
>Could you let me know how/where do you print the above "Description/Nats-Pending..."? I want to make sure that this is really the result of a protocol message received from the server.

I subscribe to:
[nats@vxr-dev-nats01 ~]$ mnats sub \$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP
18:29:07 Subscribing on $JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP 
[#1] Received on "$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP" with reply "**_INBOX.SJXVUH3BFDOD5X3DASWU7N**"
{"batch":1,"expires":4990000000}

(mnats is an alias for nats --context ....)

Then subscribe the inbox:

[nats@vxr-dev-nats01 ~]$ mnats sub **_INBOX.SJXVUH3BFDOD5X3DASWU7N**
18:30:18 Subscribing on _INBOX.SJXVUH3BFDOD5X3DASWU7N 
[#1] Received on "_INBOX.SJXVUH3BFDOD5X3DASWU7N"
Nats-Pending-Messages: 1
Nats-Pending-Bytes: 0
Status: 408
Description: Request Timeout



[#2] Received on "_INBOX.SJXVUH3BFDOD5X3DASWU7N"
Nats-Pending-Bytes: 0
Status: 408
Description: Request Timeout
Nats-Pending-Messages: 1

**Comment by kino71** [comment]
>Could you try to stop your C application and do a consumer info and make sure that the "Waiting pulls" count goes to 0?
Yes:
[nats@vxr-dev-nats01 ~]$ mnats con info QSLM LMTEMP
Information for Consumer QSLM > LMTEMP created 2023-01-18T12:13:33+01:00

Configuration:

        Durable Name: LMTEMP
           Pull Mode: true
      Filter Subject: LM.TEMP.ORDER.QS
      Deliver Policy: All
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
  Maximum Deliveries: 10
     Max Ack Pending: 5
   Max Waiting Pulls: 512

Cluster Information:

                Name: fineco_stage
              Leader: vxr-dev-nats01
             Replica: vxr-dev-nats02, current, seen 0.05s ago
             Replica: vxr-dev-nats03, current, seen 0.05s ago

State:

   Last Delivered Message: Consumer sequence: 76 Stream sequence: 6,655 Last delivery: 8h42m33s ago
     Acknowledgment floor: Consumer sequence: 76 Stream sequence: 6,648 Last Ack: 8h42m33s ago
         Outstanding Acks: 0 out of maximum 5
     Redelivered Messages: 0
     Unprocessed Messages: 0
            Waiting Pulls: 2 of maximum 512

**(process killed)** 

[nats@vxr-dev-nats01 ~]$ mnats con info QSLM LMTEMP
Information for Consumer QSLM > LMTEMP created 2023-01-18T12:13:33+01:00

Configuration:

        Durable Name: LMTEMP
           Pull Mode: true
      Filter Subject: LM.TEMP.ORDER.QS
      Deliver Policy: All
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
  Maximum Deliveries: 10
     Max Ack Pending: 5
   Max Waiting Pulls: 512

Cluster Information:

                Name: fineco_stage
              Leader: vxr-dev-nats01
             Replica: vxr-dev-nats02, current, seen 0.75s ago
             Replica: vxr-dev-nats03, current, seen 0.75s ago

State:

   Last Delivered Message: Consumer sequence: 76 Stream sequence: 6,655 Last delivery: 8h43m22s ago
     Acknowledgment floor: Consumer sequence: 76 Stream sequence: 6,648 Last Ack: 8h43m22s ago
         Outstanding Acks: 0 out of maximum 5
     Redelivered Messages: 0
     Unprocessed Messages: 0
            Waiting Pulls: 0 of maximum 512

**Comment by kozlovic** [comment]
Regarding the sub that receives those timeout: so there is no guarantee that the "408" received in that tool matches the app having a timeout with very low value (instead of 5)? I am again trying to ascertain if the C library's Fetch() really returns with a timeout after receiving this 408 (which in this case would point more to a server issue), or if it got a local timeout but by the time it goes to the next Fetch() call, it has received the 408 timeout from the previous request. In that case it would be not be too much of an issue, but could possibly be addressed. But the number of "waiting pulls" for this consumer (assuming single instance running) should be mainly at 1 (possibly 2 with the race of the new request arriving before the previous has expired), but not stay at 2 for several seconds.

**Comment by kino71** [comment]
We added logging on our app and we're positive that natsSubscriptionFetch timeout after few milliseconds instead of 5 secs.
This happens after the program is running for a while

**Comment by kozlovic** [comment]
> we're positive that natsSubscriptionFetch timeout after few milliseconds instead of 5 secs every other call

I understand, what I would want to know is if in all cases (correct timeout or short timeout), the library does receive the 408 or not. What I *hope* is simply happening is that the client times out *before* the server sends the 408 for request 1, then app goes back to another Fetch() for request 2 but then receives the response from the request 1.

**Comment by kino71** [comment]
I modified nats.c library to print the reply message headers in function:
static natsStatus
_checkMsg(natsMsg *msg, bool checkSts, bool *usrMsg, natsMsg *mhMsg)

After every pull request I print the following :

```
   struct timeval tp;
   gettimeofday(&tp, NULL);
   time_t curtime = tp.tv_sec;
   struct tm *tm = localtime(&curtime);

   char buffer[30];
   strftime(buffer, 30, "%Y/%m/%d %T", tm);
   printf("%s.%03ld\n", buffer, tp.tv_usec/1000);
    // Let's print all the keys that are currently set
        const char* *keys = NULL;
        int         nkeys = 0;
        int         i;

        s = natsMsgHeader_Keys(msg, &keys, &nkeys);
        for (i=0; (s == NATS_OK) && (i<nkeys); i++)
        {
            // To get all values that are associated with a key
            const char* *values = NULL;
            int         nvalues = 0;
            int         j;

            s = natsMsgHeader_Values(msg, keys[i], &values, &nvalues);

            for (j=0; (s == NATS_OK) && (j < nvalues); j++)
                printf("Key: '%s' Value: '%s'\n", keys[i], values[j]);

            // We need to free the returned array of pointers.
            free((void*) values);
        }
        // We need to free the returned array of pointers.
        free((void*) keys);
```

I'm currently getting :

```
2023/02/01 22:06:40.370
Key: 'Nats-Pending-Messages' Value: '1'
Key: 'Description' Value: 'Request Timeout'
Key: 'Status' Value: '408'
Key: 'Nats-Pending-Bytes' Value: '0'
_sendPullRequest reply:_INBOX.UCAPWQJH6EUW49JCBIT03C subj:$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP 
2023/02/01 22:06:45.362
Key: 'Nats-Pending-Messages' Value: '1'
Key: 'Description' Value: 'Request Timeout'
Key: 'Status' Value: '408'
Key: 'Nats-Pending-Bytes' Value: '0'
_sendPullRequest reply:_INBOX.UCAPWQJH6EUW49JCBIT03C subj:$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP 

```
(also printing reply inbox and request subject)

When (and if) the problem kick in, we should see if we get a 408, right ?

**Comment by kozlovic** [comment]
Yes, but my hope is that one of the Fetch() returns with `NATS_TIMEOUT` because it failed to get any response (even the 408), so in that case, you should see the Fetch() returns `NATS_TIMEOUT` but WITHOUT getting that protocol. On the next Fetch(), it should get the 408 "right away", this would be the 408 that was sent for the previous request.

**Comment by kozlovic** [comment]
@kino71 Assuming the issue is what I described earlier, the PR #634 should address the issue.

**Comment by kozlovic** [comment]
@kino71 The PR was merged, which closed this issue. I believe that this is what you have observed, but if trying with the library built from main you are still experiencing the problem, we will re-open this issue.

**Comment by kino71** [comment]
Hello Ivan, testing right now.
Tonight I run a test with some print added, after about 4 hours the issue showed up :

_sendPullRequest reply:_INBOX.UCAPWQJH6EUW49JCBIT03C subj:$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP 
2023/02/02 02:22:40.950
Key: 'Nats-Pending-Messages' Value: '1'
Key: 'Description' Value: 'Request Timeout'
Key: 'Status' Value: '408'
Key: 'Nats-Pending-Bytes' Value: '0'
_sendPullRequest reply:_INBOX.UCAPWQJH6EUW49JCBIT03C subj:$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP 
2023/02/02 02:22:45.943
Key: 'Nats-Pending-Messages' Value: '1'
Key: 'Description' Value: 'Request Timeout'
Key: 'Status' Value: '408'
Key: 'Nats-Pending-Bytes' Value: '0'
_sendPullRequest reply:_INBOX.UCAPWQJH6EUW49JCBIT03C subj:$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP 
2023/02/02 02:22:50.935
Key: 'Nats-Pending-Messages' Value: '1'
Key: 'Description' Value: 'Request Timeout'
Key: 'Status' Value: '408'
Key: 'Nats-Pending-Bytes' Value: '0'
**_sendPullRequest reply:_INBOX.UCAPWQJH6EUW49JCBIT03C subj:$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP 
_sendPullRequest reply:_INBOX.UCAPWQJH6EUW49JCBIT03C subj:$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP** 
2023/02/02 02:22:56.347
Key: 'Nats-Pending-Messages' Value: '1'
Key: 'Description' Value: 'Request Timeout'
Key: 'Status' Value: '408'
Key: 'Nats-Pending-Bytes' Value: '0'
_sendPullRequest reply:_INBOX.UCAPWQJH6EUW49JCBIT03C subj:$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP 
2023/02/02 02:23:00.927
Key: 'Nats-Pending-Messages' Value: '1'
Key: 'Description' Value: 'Request Timeout'
Key: 'Status' Value: '408'
Key: 'Nats-Pending-Bytes' Value: '0'
_sendPullRequest reply:_INBOX.UCAPWQJH6EUW49JCBIT03C subj:$JS.API.CONSUMER.MSG.NEXT.QSLM.LMTEMP 
2023/02/02 02:23:01.340
Key: 'Nats-Pending-Messages' Value: '1'
Key: 'Description' Value: 'Request Timeout'
Key: 'Status' Value: '408'
Key: 'Nats-Pending-Bytes' Value: '0'
 
"_sendPullRequest reply:...." is printed in js.c:1940. 
"Key:.." is printed in _checkMsg:1724 
As you can see there is a _sendPullRequest that doesn't lead to a _checkMsg, as you predicted.
I'm not sure about what you wrote in a fix comment ( "message's subject is not reqSubj") but I don't know the code that well.
Running new version with same print (and a couple more) right now.
Thanks!

**Comment by kino71** [comment]
Test program run 24 hours with no issue, I think we can consider this fixed.
Thanks!

**Comment by kozlovic** [comment]
@kino71 Thanks for the confirmation, and glad the fix was good.
