### ISSUE TITLE
Intermediate timeout errors when connecting to nats

### ISSUE THREAD

**Issue by SamirMarin** [nats-io/nats.c#633]
Currently we have a nats cluster deployed in a kubernetes cluster, we are using tls and we keep to running into a timeout error intermediately, when using the nats-io/nats.c client. I've been reproducing the timeout error using the [example/getstarted/asyncsub.c](https://github.com/nats-io/nats.c/blob/main/examples/getstarted/asyncsub.c) and the [example/getstarted/pubstr.c](https://github.com/nats-io/nats.c/blob/main/examples/getstarted/pubstr.c), I usually get the time out error every 2-3 triesc -> `Error: 26 - Timeout - (unix/sock.c:58): Timeout`. I'm testing from a pod running on aarch64 GNU/Linux node.

We also use the [nats-io/nats.go client](https://github.com/nats-io/nats.go) and have never ran into a time out error with the go client.

On the nats side we have set the tls timeout config to 5 seconds, so I do not believe this is the issue, since after increasing to 5seconds the timeout still happens intermediately at the same rate, it just takes longer to time out.

**Comment by kozlovic** [comment]
Which version of the NATS C client library are you using? Could you show the full stack reported by the library?

**Comment by SamirMarin** [comment]
Thanks for the reply!

Previously I was using 
```
library version: 3.5.1-beta
```

I have just tried it with the latest:

```
library version: 3.6.0
```

And got the same intermediate timeout error 

here is the full stack reported by the library:

```
Error: 26 - Timeout - (unix/sock.c:58): Timeout
Stack: (library version: 3.6.0)
  01 - natsSock_WaitReady
  02 - natsSock_Read
  03 - natsSock_ReadLine
  04 - _readOp
  05 - _processExpectedInfo
  06 - _processConnInit
  07 - _connect
  08 - natsConnection_ConnectTo
```

**Comment by kozlovic** [comment]
Have you tried to set the timeout option to higher than the timeout in the server, for instance `natsOptions_SetTimeout(opts, 5500)` ?

**Comment by SamirMarin** [comment]
So I just tried using [example/subscriber.c](https://github.com/nats-io/nats.c/blob/main/examples/subscriber.c):

```
./nats-subscriber -s "tls://nats:4222" -timeout 5500
```

with [example/publisher.c](https://github.com/nats-io/nats.c/blob/main/examples/publisher.c):

```
./nats-publisher -s "tls://nats:4222" -timeout 5500
```

And got a similar behaviour, intermediate timeout with the same stack output:

```
Sending 1000000 messages to subject 'foo'
Error: 26 - Timeout
Error: 26 - Timeout - (unix/sock.c:58): Timeout
Stack: (library version: 3.6.0)
  01 - natsSock_WaitReady
  02 - natsSock_Read
  03 - natsSock_ReadLine
  04 - _readOp
  05 - _processExpectedInfo
  06 - _processConnInit
  07 - _connect
  08 - natsConnection_Connect
```

I believe setting the timeout there as an args options is the same as setting with `natsOptions_SetTimeout(opts, 5500)` right?

**Comment by kozlovic** [comment]
> I believe setting the timeout there as an args options is the same as setting with natsOptions_SetTimeout(opts, 5500) right?

Not at all. Please add this line before the natsConnection_Connect() call and report back.

**Comment by SamirMarin** [comment]
I've just tested using the same two scripts adding `natsOptions_SetTimeout(opts, 5500)` before the `natsConnection_Connect()` and I have not been able to reproduce the issue since adding that setTimeout line, that seems to do it! Thank you I really appreciate the help! This can be closed out.

**Comment by kozlovic** [comment]
Glad it works. Closing the issue now.
