### ISSUE TITLE
Observing subscriber disconnections in case of message backlog

### ISSUE THREAD

**Issue by Ann-Geo** [nats-io/nats.c#662]
nats-server version used: v2.9.3
Issue: observing a bunch of subscriber disconnections.
64 subscribers are allowed to start and subscribe from a stream pre-filled with 1 million messages. And I am observing that the message reception by the subscribers is very slow and immediately a bunch of subscribers get disconnected.
Is this an expected behaviour ? What is the reason for this issue and how can it be resolved.
However this issue is not observed when the subscribers are allowed to start before filling up the stream.

**Comment by kozlovic** [comment]
You may want to upgrade the server and make sure also you run the latest on the client side. But what it looks to me is that your JetStream consumer does not have flow control enabled, so when the subscription is registered, the server floods the client library with data, the client library may not be able to ingest that as fast as the server can send and therefore the server cuts the connection off as a slow consumer, likely with max pending message size reached? You did not provide what error is reported (server or client, and what it is, so this is just a suspicion).

**Comment by Ann-Geo** [comment]
Thank you for the reply. Working on updating server and getting more data. Will get back in few days.

**Comment by Ann-Geo** [comment]
This issue is not observed when latest nats server version is used. Thanks.
