### ISSUE TITLE
The protobuf-c and ssh libraries are looked for when using the cnats static library.

### ISSUE THREAD

**Issue by li1786422** [nats-io/nats.c#678]
### What version were you using?

natsclient 3.61

### What environment was the server running in?

Static libraries generated by vs code cmake on windows using the visio studio 2022 compiler (for x64 architectures).

### Is this defect reproducible?

When using the cnats static library, the link will look for protobuf-c libraries, and when generating the cnats library, the static library of protobuf-c is used.

### Given the capability you are leveraging, describe your expectation?

Use the cnats library without relying on any other libraries.

### Given the expectation, what is the defect you are observing?

Problems with static library generation mechanism under windows or cmake writing

**Comment by levb** [comment]
@li1786422 Are you observing this when linking the example apps? There was a recent [conversation](https://natsio.slack.com/archives/C01AWP40KGF/p1692203761037549) about it in the #C channel on Slack.

A quick workaround could be: if you are not using the now-deprecated NATS Streaming (aka STAN), you can compile with -`DNATS_BUILD_STREAMING=OFF`. STAN is the only part of the code that has a libprotobuf-c dependency.

**Comment by levb** [comment]
@li1786422 Did my suggestion above work for you?

**Comment by li1786422** [comment]
ok I will try it

**Comment by li1786422** [comment]
but jetstream also use libprotobuf-c to encode

**Comment by li1786422** [comment]
please nat-c  have the ues of  key-value example?

**Comment by kozlovic** [comment]
> but jetstream also use libprotobuf-c to encode

@li1786422 No, JetStream does not need libprotobuf-c, the protocols are JSON.

> key-value example?

We don't have examples per-se, but you could have a look at the tests, this should give you all the help you need. Check tests that start with `test_KeyValue`:
- https://github.com/nats-io/nats.c/blob/63dbd8631a7ce3a0e5fb6707653e967ca6842712/test/test.c#L30529
- https://github.com/nats-io/nats.c/blob/63dbd8631a7ce3a0e5fb6707653e967ca6842712/test/test.c#L30660C3-L30660C3
- etc..

**Comment by li1786422** [comment]
ok

**Comment by li1786422** [comment]
Is it possible to set the lifetime of a message on jetstream, I only found a MaxAge in the jetStreamConfig but I don't know if it's relevant.

**Comment by kozlovic** [comment]
@li1786422 No, you cannot set a TTL per-message. It is only at the stream level.

**Comment by li1786422** [comment]
please 
What is the meaning of MaxAge in jetStreamConfig, is it in years, months, days or seconds?

**Comment by li1786422** [comment]
Please 
set the survival of a message to be limited only from MaxMsgSize, jsDiscardPolicy?

**Comment by li1786422** [comment]
> @li1786422 No, you cannot set a TTL per-message. It is only at the stream level.
Please
set the survival of a message to be limited only from MaxMsgSize, jsDiscardPolicy?and What is the meaning of MaxAge in jetStreamConfig, is it in years, months, days or seconds?

**Comment by kozlovic** [comment]
@li1786422 You will find more information about the stream configuration [here](https://docs.nats.io/nats-concepts/jetstream/streams). MaxAge is the time to live of messages in the stream expressed in nanoseconds (this comes from Go time.Duration that is an int64 and the unit is nanoseconds).

**Comment by li1786422** [comment]
Thanks Sorry I only looked in the source code and didn't find that explanation.

> @li1786422[您可以在此处](https://docs.nats.io/nats-concepts/jetstream/streams)找到有关流配置的更多信息。MaxAge 是流中消息的生存时间，以纳秒表示（这来自 Go time.Duration，是一个 int64，单位是纳秒）。
Thanks Sorry I only looked in the source code and didn't find that explanation.

**Comment by li1786422** [comment]
Please use js_SubscribeSync(&sub, js, subj, &jsOpts, NULL, NULL); to subscribe to a topic, and after that subscribe to a topic by while(1){
          natsSubscription_NextMsg(&msg, sub, 5000);
            if (s ! = NATS_OK)
                break;

            if (start == 0)
            start = nats_Now(); s = natsMsg_NextMsg(sub, 5000); 
           if (s ! = NATS_OK)
            
            s = natsMsg_Ack(msg, nullptr);
            The method natsMsg_Destroy(msg);
} 
keeps printing the data, what is the reason for the garbled order of the fetched data

**Comment by kozlovic** [comment]
@li1786422 I am not sure I understand your question. Are you saying that messages "1, 2, 3, 4, 5" are in the stream and using the code above you don't see messages "1, 2, 3, 4, 5" being received? We would need to see the content of the subscribe options to see for instance if you have created a queue (and have multiple instances running) instead of a regular consumer, or if you have a MaxAckWait that is way too small (smaller than your sleep interval) that then causes the server to redeliver messages.

Also, I would prefer that either we close this issue (related to CMake) if the original problem is somehow addressed and that you open new issues when dealing with different questions/issues. Is that ok?

**Comment by li1786422** [comment]
ok

> @li1786422我不确定我是否理解你的问题。您是说消息“1,2,3,4,5”在流中，并且使用上面的代码您没有看到消息“1,2,3,4,5”被接收？我们需要查看订阅选项的内容，例如您是否创建了一个队列（并且运行了多个实例）而不是普通消费者，或者您的 MaxAckWait 是否太小（小于您的睡眠）间隔），然后导致服务器重新传送消息。
> 
> 另外，我希望如果原始问题以某种方式得到解决，我们可以关闭此问题（与 CMake 相关），并且在处理不同的问题/问题时打开新问题。这可以吗？

okI t is possible to close this issue and create a different issue to discuss it again

**Comment by li1786422** [comment]
this question I have commited ,The issue  is Subscription Data Disorder Problem #690

> @li1786422 I am not sure I understand your question. Are you saying that messages "1, 2, 3, 4, 5" are in the stream and using the code above you don't see messages "1, 2, 3, 4, 5" being received? We would need to see the content of the subscribe options to see for instance if you have created a queue (and have multiple instances running) instead of a regular consumer, or if you have a MaxAckWait that is way too small (smaller than your sleep interval) that then causes the server to redeliver messages.
> 
> Also, I would prefer that either we close this issue (related to CMake) if the original problem is somehow addressed and that you open new issues when dealing with different questions/issues. Is that ok?
this question I have commited ,The issue  is Subscription Data Disorder Problem #690 
 Please help me with the answer thanks

**Comment by levb** [comment]
Closing since the original issue is resolved, and the new ticket filed
