### ISSUE TITLE
jetstream

### ISSUE THREAD

**Issue by li1786422** [nats-io/nats.c#683]
### What version were you using?

server : nats-server2.9.21

### What environment was the server running in?

windows10 cpu ：i9-12900

### Is this defect reproducible?

yes

### Given the capability you are leveraging, describe your expectation?

jetstream: set the jetstream parameter MaxMsgs to 1, the publisher of the topic on the jetstream every 10s to publish a message, the storage method memory storage, the other is the default, when subscribing to the topic on the jetstream when the first one-time direct subscription to two messages, after the normal return message.

### Given the expectation, what is the defect you are observing?

jetstream: set the jetstream parameter MaxMsgs to 1, the publisher of the topic on the jetstream every 10s to publish a message, the storage method memory storage, the other is the default, when subscribing to the topic on the jetstream when the first one-time direct subscription to two messages, after the normal return message.

**Comment by kozlovic** [comment]
I am not sure I fully understand what the issue is. Would you mind posting the code you used to reproduce the issue?

**Comment by kozlovic** [comment]
@li1786422 On that issue, do you have more information or should it be closed?

**Comment by li1786422** [comment]
> @li1786422 On that issue, do you have more information or should it be closed?



> @li1786422 On that issue, do you have more information or should it be closed?

I'm sorry I forgot about that I've fixed it and can close it now
