### ISSUE TITLE
The protobuf-c  libraries are looked for when using the cnats static library

### ISSUE THREAD

**Issue by li1786422** [nats-io/nats.c#692]
### Observed behavior

Problems with static library generation mechanism under windows or cmake writing and  And I set the -DNATS_BUILD_STREAMING=OFF. After that, the compiled static library still looks for the protobuf-c library

### Expected behavior

Use the cnats static library without relying on any other libraries.

### Server and client version

nats-server is 2.9.21
natsclient-c 3.61

### Host environment

windows10 cpu ：i9-12900

**Comment by kozlovic** [comment]
I cannot reproduce this. Could you send us the CMakeCache.txt present in the build directory and how do you find out that it still searches for the protobuf library?

**Comment by kozlovic** [comment]
I have a Windows VM and I have make sure that the directory where the pbuf is located is renamed. If I compile with Streaming support, compilation fails (as expected). If I disable it and also ask to compile only static library (and examples), compilation succeeds. When running the examples/nats-subscriber.exe program (statically compiled), it starts without complaining about the protobuf library.

**Comment by li1786422** [comment]
Thanks for your reply It might be because of my previous changes to CMakeLists I'll re-download it again from github and try it again Maybe it's because I changed CMakeLists before, I'll try it again by downloading it from github.

**Comment by levb** [comment]
@li1786422 Are you still experiencing this issue, or can the ticket be resolved now?
