### ISSUE TITLE
microservices header missing

### ISSUE THREAD

**Issue by geiseri** [nats-io/nats.c#701]
### Observed behavior

The header `micro_args.h` is missing from the install files.

### Expected behavior

It is added to the install section of [src/CMakeLists.txt](https://github.com/nats-io/nats.c/blob/29dcecc42afc454b7328ee7c3b1aba761689339a/src/CMakeLists.txt#L83)

### Server and client version

release 3.7.0

**Comment by geiseri** [comment]
Noted by the header contents that it is incomplete maybe this is blocking based on completion so feel free to close.

**Comment by kozlovic** [comment]
@geiseri Since v3.7.0, the service framework was released, so I think this header should have been included indeed, even if there are still TODOs. Will create a PR to address that.

**Comment by kozlovic** [comment]
@geiseri Actually, having second thoughts. This is used only for the examples, and not sure that it was intended to be library-level APIs. Asking @levb what we should be doing with that header file.

**Comment by geiseri** [comment]
@kozlovic looking at the internals maybe it should be in the examples directory.  The "args format" looks like is specific to the example as it wouldn't have enough of a schema for interop.

**Comment by levb** [comment]
micro-args was kind of a stop-gap TBH, for examples only. I will move it there.

**Comment by levb** [comment]
Moving `micro_args.*` to `./examples` would be rather involved since the `CMakeLists.txt` builds an executable for every `.c` file.

Moving `micro_args.h` only, and leaving `micro_args.c` in `./src` can be confusing.

0/5 we should just leave the files where they are, and perhaps replace the use of `micro_args` in the examples with  another, OSS serialization package? Initially I didn't want to pull in the dependencies even for the examples, but using JSON or some other common format would probably be preferred?

@geiseri @kozlovic ?

**Comment by kozlovic** [comment]
@levb Maybe the "mistake" was to make this example program a bit too configurable ;-). The parameters could have been hard coded, in that the value of the examples was to show how to use the service APIs, not really to be able to run actual fibonnaci or factorial computations :-)

But I would not want to pull a JSON dependency just for that. As you said, we have tried hard to limit the dependencies, so it would be a shame to add one just for the examples. Note that most of the build issues reported by users are around the protobuf (to compile the NATS Streaming client).

**Comment by levb** [comment]
I agree. For now, I am proposing a PR that moves all this serialization business into a single .h file under examples. Will make `Help wanted` tickets for more, simpler examples.

**Comment by geiseri** [comment]
@levb did you make that ticket?  I have some ideas on that.
