### ISSUE TITLE
vcpkg_link_err

### ISSUE THREAD

**Issue by goumanghd** [nats-io/nats.c#702]
### Observed behavior

e.g file  cnats-targets-debug.cmake 

list(APPEND _cmake_import_check_targets cnats::nats )
list(APPEND _cmake_import_check_files_for_cnats::nats "${_IMPORT_PREFIX}/debug/lib/natsd.lib" "${_IMPORT_PREFIX}/debug/ -->bin/natsd.lib<---" ) --->err<---

### Expected behavior

list(APPEND _cmake_import_check_targets cnats::nats )
list(APPEND _cmake_import_check_files_for_cnats::nats "${_IMPORT_PREFIX}/debug/lib/natsd.lib" "${_IMPORT_PREFIX}/debug/ -->bin/natsd.dll<---" ) --->success<---

note: such err total two  , you can search by [bin/natsd.lib] [lib/natsd.dll] , you will get the err point.

### Server and client version

 vcpkg
{
  "name": "cnats",
  "version": "3.6.0"
}

**Comment by kozlovic** [comment]
Sorry, but that is outside of the scope of this repository. I would recommend that you follow up [there](https://github.com/microsoft/vcpkg/tree/master/ports/cnats) maybe.
